src/data/timeline.yml

In this PR, I'm adding events from March - May to the project timeline. 
@tylersticka @saralohr @mrgerardorodriguez @grigs

Add recent events to the project timeline

---

src/assets/drizzle/styles/base/config.css
src/assets/drizzle/styles/components/swatch.css
src/assets/drizzle/styles/components/timeline.css
src/assets/drizzle/styles/vendor/prism.css
src/data/colors.yml
src/pages/index.hbs
src/templates/drizzle/swatch.hbs

---
@saralohr @mrgerardorodriguez

Some style guide tweaks

---

src/assets/toolkit/styles/components/float-label.css
src/assets/toolkit/styles/components/sky.css

cc @tylersticka @mrgerardorodriguez

Header contrast adjustment

---

src/assets/toolkit/scripts/home-animation.js
src/data/posts.yml
src/pages/sandbox/tyler-home-a.hbs
src/static/images/sandbox/home-animation.svg

Whereas #233 focused on the header area, this one focuses primarily on the content area (though there are a handful of small tweaks to the header).
It's still a WIP... lots of ugly inline styles, one missing image and one unresolved one. I'm issuing a PR as-is so folks can see it in the browser and provide feedback on the direction before getting _too_ in the weeds with those individual problems.
---
@saralohr @mrgerardorodriguez @erikjung

More WIP homepage progress

---

src/pages/sandbox/tyler-home-a.hbs

`u-flexGrow1` was not behaving as expected in Safari.
---
@saralohr @mrgerardorodriguez

Fix Safari issue with bottom-aligned CTAs

---

src/assets/toolkit/styles/components/cms-content.css
src/assets/toolkit/styles/components/index.css
src/pages/pages/blog-single-article.hbs
src/patterns/combos/cms-content/base.hbs

Add style to `pre` for WP-entered content. Couldn't think of anything else to add at the moment.
cc @mrgerardorodriguez @tylersticka

Feature: CMS class

---

src/templates/toolkit/page-segue.hbs

re: https://trello.com/c/t7UmrczV/208-replace-squiddly-doo-with-actual-cta
cc @tylersticka @nicolemors @saralohr @mrgerardorodriguez

updating CTA with more sensible but much less fun phrasing

---

src/assets/toolkit/scripts/toolkit.js
src/assets/toolkit/styles/vendor/prism.css
src/pages/pages/blog-single-article.hbs

---
@saralohr @mrgerardorodriguez 
Fixes #267

Add PHP syntax highlighting

---

src/assets/toolkit/styles/utils/display.css

Necessary for my solution to cloudfour/cloudfour.com-wp#62
---
@mrgerardorodriguez

Add more responsive u-block variations

---

src/assets/toolkit/styles/utils/flex.css
src/assets/toolkit/styles/utils/size.css

Add a couple utilities for a bug fix for IE 11. 
cc @tylersticka @mrgerardorodriguez 
Will fix Issue #11 once theme template is updated.

Add utilities for flex shrink and width full

---

src/assets/toolkit/styles/components/cms-content.css

Mistakenly used wrong JetPack class name. Fixed it, form should look legit now.
@tylersticka @saralohr @aileenjeffries @mrgerardorodriguez

Device Lab Form - Class name fix

---

package.json
src/assets/toolkit/scripts/lib/component/comment-reply.js
src/assets/toolkit/scripts/toolkit.js
src/pages/pages/blog-single-article.hbs
src/patterns/combos/blog/post-comment-form.hbs
src/patterns/combos/blog/post-comment.hbs

For background: cloudfour/cloudfour.com-wp#198
Making this so @mrgerardorodriguez and @erikjung have something to easily review.

CommentReply JS component

---

src/assets/toolkit/scripts/lib/component/comment-reply.js

Was tearing my hair out with this and it turns out I'm a dumb dumb.
---
@mrgerardorodriguez @erikjung

Fix dumb typo because I’m a stupid 🐒

---

src/patterns/utilities/bg.hbs
src/patterns/utilities/border.hbs
src/patterns/utilities/columns.hbs
src/patterns/utilities/display.hbs
src/patterns/utilities/flex.hbs
src/patterns/utilities/layout.hbs
src/patterns/utilities/link.hbs
src/patterns/utilities/list.hbs
src/patterns/utilities/offset.hbs
src/patterns/utilities/position.hbs
src/patterns/utilities/size.hbs
src/patterns/utilities/space.hbs
src/patterns/utilities/text.hbs

This PR includes the progress I made this morning documenting utilities. It is not complete, but there are placeholder docs in place for all remaining work.
Submitting this now since I have to move to another task today. Figured better to have _most_ of them documented than none of them!

Utility documentation

---

src/assets/toolkit/scripts/lib/component/slideshow.js
src/assets/toolkit/scripts/toolkit.js
src/assets/toolkit/styles/components/index.css
src/assets/toolkit/styles/components/slideshow.css
src/assets/toolkit/styles/utils/display.css
src/assets/toolkit/styles/utils/text.css
src/pages/pages/team-single.hbs
src/patterns/components/slideshow/base.hbs
src/patterns/utilities/display.hbs
src/patterns/utilities/text.hbs

I decided to open a new PR for this to keep things cleaner. You can reference PR #337 to see some of the feedback addressed here.
Requesting JS review @erikjung or @mrgerardorodriguez.
cc @tylersticka

Add trivia slider

---

src/assets/toolkit/scripts/lib/component/slideshow.js
src/pages/pages/team-single.hbs
src/patterns/components/slideshow/base.hbs

This updates our pattern with a few changes made when implementing this in the theme [PR #292](https://github.com/cloudfour/cloudfour.com-wp/pull/292).
cc @tylersticka @mrgerardorodriguez

Chore update slideshow

---

src/patterns/components/input/elastic-textarea.hbs
src/patterns/components/input/float-label-dark.hbs
src/patterns/components/input/float-label.hbs
src/patterns/components/sky/collection.yaml

@saralohr @mrgerardorodriguez @erikjung @nicolemors 
Fixes #349

Remove outdated labels from patterns

---

README.md

Because I always forget it.
---
cc: @saralohr @erikjung @nicolemors

Add Netlify URL to README

---

src/static/manifest.json

Chore: Update `display` to `standalone`

---

src/assets/toolkit/scripts/toolkit.js
src/assets/toolkit/styles/vendor/prism.css
src/pages/pages/blog-single-article.hbs

Add JSON highlighting

---

src/pages/pages/home.hbs

This PR updates the home page to match the change in the WP repo in https://github.com/cloudfour/cloudfour.com-wp/pull/359.

Chore: Update home page

---

src/static/manifest.json

Of reference: https://github.com/cloudfour/cloudfour.com-wp/issues/360
Closes #391

Chore: Remove escape slashes

---

src/assets/toolkit/styles/components/pagination.css

See code comments for detailed explanation.
---
Fixes #410

Address Safari flexbox bug in Pagination

---

src/static/_headers

Well, that was fun. Trying #412 again here, with a wildcard addition. 
(Can't test this locally, unfortunately.)

Add wildcard to make it actually work

---

src/pages/pages/case-study-single.hbs
src/pages/sandbox/case-study-single-a.hbs

This PR swaps two insecure assets we were attempting to load with secure ones. This should prevent future Netlify warnings about these.

Replace insecure assets

---

src/assets/toolkit/styles/vendor/prism.css
src/patterns/components/cms-content/base.hbs

I was about to update the theme to include the highlighting improvements introduced in #460, but I saw an opportunity to improve string highlighting. This colorizes strings in JavaScript differently as well as interpolation in string templates.

Better string highlight

---

.github/workflows/ci.yml
.storybook/main.js
package-lock.json
package.json
src/demo/heading/heading.stories.js

Closes #496
Sets up `prettier` + `eslint` and it runs both on CI.
`npm run lint`
`npm run check-lint`

Add JS Linting

---

src/base/_typography.scss
src/design-tokens/_font-family.yml
src/design-tokens/_font-weight.yml
src/design-tokens/font.yml
src/design/typography/demo/blockquote.twig
src/design/typography/demo/code-block.twig
src/design/typography/demo/headings.twig
src/design/typography/demo/list-description.twig
src/design/typography/demo/list-ordered.twig
src/design/typography/demo/list-unordered.twig
src/design/typography/demo/paragraphs.twig
src/design/typography/typography.stories.mdx
src/objects/button/button.scss

Adds a group of font family and weight tokens and applies those to relevant stylesheets. Also introduces a new Typography story file populated with specimens, most of which are currently unstyled.
---
- See #470

Font tokens and WIP typographic specimens

---

src/components/calendar-date/calendar-date.scss
src/components/calendar-date/calendar-date.stories.mdx
src/components/calendar-date/calendar-date.twig
src/components/calendar-date/demo/seasons.twig
src/components/calendar-date/demo/styles.scss

Revised version of our [existing Calendar Date component](https://cloudfour-patterns.netlify.com/patterns/components/calendar-date.html), with a few noteworthy changes:
- Added optional note instead of multi-range version that had questionable markup.
- Improved contrast of header.
- Seasonal color variations.
---
- Resolves #494

Calendar Date component

---

CONTRIBUTING.md
README.md
src/welcome.stories.mdx

This commit moves the contribution instructions to `CONTRIBUTING.md` and adds installation instructions to `README.me` and the welcome story for Storybook.
---
- Fixes #626

Update Readme Files

---

CONTRIBUTING.md
package-lock.json
package.json

Need these changes to make a release.

Release 0.2.0

---

renovate.json

This commit adds the `automergeMinor` preset: https://docs.renovatebot.com/presets-default/#automergeminor

Add automergeMinor Preset

---

renovate.json

Based on slack discussion
Goals:
- Reduce Netlify build minutes for deploy previews
- Reduce noise

Change renovate settings

---

.changeset/dirty-pets-act.md
.changeset/slimy-gifts-drum.md
.github/workflows/changesets.yml
CHANGELOG.md

Use built in GitHub token and update changelog

---

.changeset/silent-planes-boil.md
src/components/input/elastic-textarea.ts

We made some updates to this code in another project that's using it,
so this commit is updating this version to match.
Review the [elastic textarea pattern](https://deploy-preview-1016--cloudfour-patterns.netlify.app/?path=/docs/components-input--elastic-textarea). There should be no visible or functional changes.

Update Elastic Textarea JS

---

.changeset/clean-lamps-appear.md
.changeset/late-tomatoes-matter.md
src/components/sky-nav/sky-nav.stories.mdx
src/components/sky-nav/sky-nav.ts
src/components/sky-nav/sky-nav.twig

Closes #1137 
1. Open [Sky Nav](https://deploy-preview-1239--cloudfour-patterns.netlify.app/?path=/story/components-sky-nav--dark)
2. Resize to small screen
3. Toggle the menu, make sure that it animates correctly, and the content is hidden/shown correctly

Add animation to sky nav

---

.changeset/seven-dodos-deliver.md
src/components/avatar/avatar.stories.mdx

This PR updates the Avatar component story code example.
Left: Before
Right: After
1. Review story code examples
2. Confirm no regressions
---
- See #1289

Make the Avatar story code examples better

---

src/components/checkbox/checkbox.stories.mdx

This PR refines the Checkbox component story code examples.
Left: Before
Right: After
1. Review the Checkbox component story code examples and confirm they are accurate.
---
- See #1289

Refine Checkbox story code examples

---

renovate.json

https://github.com/cloudfour/cloudfour.com-patterns/pull/1280#issuecomment-867915815

Change renovate options for @wordpress/block-library

---

src/components/ground-nav/ground-nav.stories.mdx

This PR refines the Ground Nav PWA Stats story code example.
Preview: https://deploy-preview-1359--cloudfour-patterns.netlify.app/?path=/docs/components-ground-nav--pwa-stats
1. Review the Ground Nav PWA Stats code example for accuracy
---
- See #1289

Refine Ground Nav story code example

---

src/components/sky-nav/sky-nav.stories.mdx

This PR refines the SkyNav component code examples.
Preview: https://deploy-preview-1424--cloudfour-patterns.netlify.app/?path=/docs/components-sky-nav--dark
1. Review the SkyNav component story code examples for accuracy
---
- See #1289

Refine SkyNav component code examples

---

src/objects/bunch/bunch.stories.mdx

Improve source code example for o-bunch

---

src/objects/container/container.stories.mdx

See title.
---
- See #1447
/CC @person

Improve container source examples

---

src/objects/page/demo/example.twig
src/objects/page/page.stories.mdx

Improve page source example

---

src/objects/rhythm/demo/article.twig
src/objects/rhythm/demo/intro.twig
src/objects/rhythm/demo/list.twig
src/objects/rhythm/demo/sections.twig
src/objects/rhythm/demo/summary.twig
src/objects/rhythm/rhythm.stories.mdx

Improve rhythm source examples

---

src/design/colors.stories.mdx
src/prototypes/card-variations/example/example.scss

Fix the names of primary brand colors on docs page

---

.github/workflows/ci.yml

@see https://github.com/nodejs/node/pull/42017

cancel running CI jobs when a PR is updated

---

CONTRIBUTING.md
README.md
src/components/ground-nav/demo/pwa-stats.twig

Figured I'd make these quick changes. 🙂

Update master to main in docs

---

.changeset/funny-actors-approve.md
src/mixins/_fluid.scss
src/objects/bio/bio.scss
src/objects/bio/bio.twig
src/objects/bio/demo/demo.twig
src/tokens/size/sizing.js

This PR fixes a few design issues with the Bio object.
Changes include:
- meta content is now centered on larger viewports
- meta content is now closer to avatar vertically on larger viewports
- grid gap below Bio content is now removed on larger viewports
- `o-bio__avatar` now has width restraints
- the Bio content is wrapped in a prose container 
- a `size.$square-avatar-large` token was added
&nbsp; | Before | After
--- | --- | ---
Smaller Viewports | ![screencapture-v-next-cloudfour-patterns-netlify-app-iframe-html-2022-04-25-07_10_13](https://user-images.githubusercontent.com/459757/165108529-390af720-5284-4c61-8853-aec75b25a8ae.png) | ![screencapture-localhost-6006-iframe-html-2022-04-25-07_10_40](https://user-images.githubusercontent.com/459757/165108537-7205e1c0-4e4e-4a51-9d2b-30b6 …

Fix Bio object design inconsistencies

---

.changeset/chilled-snails-give.md
.changeset/flat-emus-remain.md
src/components/cloud-cover/cloud-cover.scss
src/components/cloud-cover/cloud-cover.stories.mdx
src/components/cloud-cover/cloud-cover.twig
src/components/cloud-cover/demo/content.twig
src/components/cloud-cover/demo/extra.twig
src/components/cloud-cover/demo/scene.twig

This PR increases the font size of the cloud cover content on wider screen sizes.
1. [Deploy link](https://deploy-preview-1828--cloudfour-patterns.netlify.app/?path=/story/components-cloud-cover--content)
Fixes https://github.com/cloudfour/cloudfour.com-patterns/issues/1822
---

Increase font size on larger screens

---

.renovaterc.json

Don't auto-merge storybook renovate PR's

---

.changeset/afraid-candles-sort.md
src/components/subscribe/subscribe.stories.mdx
src/components/subscribe/subscribe.twig

Closes https://github.com/cloudfour/cloudfour.com-patterns/issues/1881
https://deploy-preview-1892--cloudfour-patterns.netlify.app/?path=/docs/components-subscribe--default-story
Try out the props editor and make sure that everything works as expected

Change the subscribe component to use the heading component

---

src/components/input/elastic-textarea.ts

https://gist.github.com/seanmhanson/fe370c2d8bd2b3228680e38899baf5cc

Avoid Ableist Language
