- .babelrc
- config.js
- package.json
- src/assets/toolkit/scripts/home-animation.js
- src/pages/sandbox/tyler-home-a.hbs
- src/static/images/sandbox/home-animation.svg
This PR adds a WIP home prototype to the sandbox that showcases the current state of the homepage animation and accompanying header text.
The animation is entirely separate from the rest of the toolkit. The imagery exists in an external SVG, which then references a JS file that is separate from our main `toolkit.js`.
For performance and, honestly, usability of constructing a timeline-based animation, I chose to use GSAP. This means the animation JavaScript adds up to a whopping `318kb` uncompressed. This compresses down to `138kb` with Uglify, and further down to `37kb` when gzipped. The gzipped SVG is only `918b`, so we're looking at a total `38kb` transferred for the animation currently, which seems like a reasonable amount to load (and far lighter than the average full-bleed photo). …
> WIP: Home prototype header

- src/assets/toolkit/styles/components/figure.css
- src/assets/toolkit/styles/toolkit.css
- src/assets/toolkit/styles/vendor/wordpress.css
This PR adds styles for the WP generated classes, and accounts for some width and height inline styles and attributes applied by Wordpress that make for images that don't scale proportionally (or, at all).
For the `.Figure` component, I made it a mixin so that these styles could be applied to the WP `<figure>` class, oddly named `wp-caption` (I believe it's named this because images are only wrapped in a `<figure>` element if they have been provided a caption within the WP media dialogue).
cc @mrgerardorodriguez @tylersticka @erikjung @aileenjeffries
> Add styles for WP generated classes

- src/pages/pages/case-study-core.hbs
re: https://trello.com/c/rFdXFU9e/201-chore-make-case-studies-core-header-more-consistent-in-terms-of-spacing-and-font-size-with-other-section-headers#
I was going to just tackle the header but it looks like this pattern was made before we switched a few things around in the templates. I used `talk-core.hbs` as an example. 
Old heading:
New heading:
The subheading is pretty long compared to other pages, but I think it looks fine.
cc @tylersticka @nicolemors
> matching Our Work to other core pages

- src/assets/toolkit/styles/base/typography.css
- src/pages/sandbox/tyler-what_sets_us_apart-c.hbs
- src/patterns/typography/blockquote.hbs
Line breaks were resulting in citation content breaking to new line without dash. This removes the whitespace and injects some via CSS to overcome the issue.
---
@saralohr @mrgerardorodriguez @nicolemors @aileenjeffries
> Fix blockquote cite break issue

- src/assets/toolkit/styles/components/sky.css
- src/patterns/components/sky/base.hbs
- src/templates/toolkit/global-footer.hbs
- src/templates/toolkit/page-segue.hbs
I was _one_ page too optimistic when I designed nav stuff last year. So close! 😆 
This makes some nav-related tweaks...
1. Adds the latest nav item to the header and footer. (I do not know if these labels are final.)
2. Adjusts the `--Sky-nav-*-viewport` media queries to account for this change.
3. Adjusts the global footer since we've toppled the symmetry of the footer nav.
4. Makes two small tweaks tot he page segue that were bugging me.
---
@saralohr @mrgerardorodriguez @nicolemors @aileenjeffries
> Global nav tweaks

- src/assets/toolkit/scripts/toolkit.js
- src/pages/pages/blog-single-article.hbs
This PR includes Prism's SCSS component for syntax highlighting.
---
@saralohr @mrgerardorodriguez @grigs
> Add SCSS syntax highlighting

- src/assets/toolkit/styles/utils/list.css
- src/pages/pages/blog-single-article.hbs
Allows lists with markers still visible to use CSS columns without breaking visually.
---
@saralohr @mrgerardorodriguez
> Add u-listColumns utility + example

- src/assets/toolkit/styles/base/typography.css
Without smarter hyphenation in browsers and more predictable justified text, this just isn't as readable. I like that it maintains more consistently boxy shapes of text, but that's not worth the readability tradeoffs. It is text, after all!
This only affects Firefox and Safari. Screenshots below are from Firefox, which has the unique distinction of _not_ breaking "date-sensitive" at the hyphen for some reason. _Oh, Firefox, you card..._
---
@saralohr @mrgerardorodriguez @aileenjeffries @megnotarte 
Fixes #269
> Remove default hyphenation

- src/assets/toolkit/styles/base/base.css
- src/assets/toolkit/styles/base/typography.css
In practice, this didn't work so great with our content.
Now, code blocks with very long lines will scroll horizontally.
---
@saralohr @mrgerardorodriguez 
Fixes #272
> Don't wrap code blocks

- src/pages/pages/blog-single-article.hbs
This big scary diff is just just me wrapping the post content in a `<div>`, moving `u-spaceItems1` there and adding `u-cf` so floats will be contained.
Look at how well-contained this float is, for goodness' sake:
Template will need updating in WP as well.
---
@saralohr @mrgerardorodriguez 
See: #270
> Clear lingering floats in single post content

- config.js
- package.json
Running `npm start` will run our Gulp tasks in development mode, without compression (as always).
WIth these changes (which ape how we did things on our last WP project), we now use that boolean to determine whether or not to optimize assets.
Running `npm run build` (or any of the `gulp` tasks without the `--dev` flag) will minify the assets.
I also corrected the `build` script definition as it had an error (was missing the `run` argument).
---
@mrgerardorodriguez @saralohr
> Support optimization of CSS and JS

- src/assets/toolkit/styles/base/base.css
Re: https://github.com/cloudfour/cloudfour.com-patterns/pull/281
This adds a base `width` and `height` to the `<iframe>` element. This allows the `FlexEmbed` component to be happy.
---
cc: @erikjung @tylersticka @saralohr
> Add width/height to base iframe

- src/assets/toolkit/styles/components/cms-content.css
RE: https://trello.com/c/WMM4cQ0r/264-style-device-lab-form
Added in styes for the JetPack Device Lab Form in the `.CmsContent` component.
`.comment-form` and `.pushbutton-wide` are both JetPack classes.
It should look like this:
@tylersticka
> Styles for Device Lab Form

- src/assets/toolkit/styles/components/calendar-date.css
re: https://github.com/cloudfour/cloudfour.com-patterns/issues/298
Hopefully, I'm not under thinking this - adding `overflow:hidden` to the containing element rounds the top corners of the pink heading in our calendar dates. 
cc @tylersticka @nicolemors @saralohr @mrgerardorodriguez
> rounding month heading corners to fix #298

- src/assets/toolkit/styles/components/table.css
cc @tylersticka @mrgerardorodriguez @aileenjeffries 
Fixes Issue #301
> Make table scroll horizontally when it overflows

- src/static/images/icons/speakerdeck.svg
Even though I have a 24x24 viewbox on the speakerdeck icon, it wasn't vertically aligning nicely with text. By tweaking the viewbox, it now lines up more nicely. 
cc @tylersticka specifically because you'll be able to tell me if this is the wrong way to fix this.
> adjusting speakerdeck icon viewbox

- src/assets/toolkit/scripts/lib/component/float-label.js
- src/assets/toolkit/scripts/toolkit.js
- src/patterns/combos/blog/post-comment-form.hbs
- src/patterns/components/input/float-label/base.hbs
When we decided to move away from Modernizr for solutions that didn't block the page load, we lost their `oninput` event check. Our solution at the time was to overtly specify the `keyup` event for float labels, which seemed a fine solution.
But as described in #311, that event will only fire when keys are literally pushed, at least in some browsers. This meant that alternative means of filling out the forms, such as autofill or pasting text from a right-click, would not trigger the active state consistently.
This PR removes the `eventName` option from our `FloatLabel` component, instead using [a very simple technique](https://mathiasbynens.be/notes/oninput) for detecting `oninput` support and falling back to `keyup` otherwise.
To appropriately test this, I added [autofill …
> Graceful degradation for FloatLabel events

- src/assets/toolkit/styles/components/sky.css
I made some small adjustments to the navigation to reduce awkward wrapping. What I did:
- removed the left margin on the ul with the class name of `Sky-nav-menu-items`.
- reduced the breakpoint for the `--Sky-nav-full-viewport` variable from 65em to 45em (the point where all nav items fit in one line)
- At this same breakpoint, I reduced the left and right padding on the links from 1em to 0.5em. This also helps to get everything on one line in smaller screens. Because the list items space out at this breakpoint, the screen size range where the links are actually only 0.5em + 0.5em away from each other is very brief and they quickly expand outward. 
- In the lg breakpoint, I switched the font size from md to sm, because the font size increase was wrapping links again. I increased the font …
> Minimizing wrapping in the navigation

- src/static/manifest.json
This was accidentally updated in the wrong repo, and I’m tired of seeing it updated whenever the pattern tasks run in our theme.
Also converted tabs to spaces because YOLO.
See: cloudfour/cloudfour.com-wp#170
---
@mrgerardorodriguez @erikjung
> Update manifest.json based on latest from WP

- src/assets/toolkit/styles/components/footnote-link.css
- src/assets/toolkit/styles/utils/bg.css
- src/assets/toolkit/styles/vendor/index.css
- src/assets/toolkit/styles/vendor/jetpack-markdown.css
This begins to address cloudfour/cloudfour.com-wp#255 by customizing the markup [Jetpack Markdown](https://en.support.wordpress.com/markdown-quick-reference/) outputs for footnotes.
I went this route after confirming that there are no documented filters for the footnotes, and any that existed in the underlying library are not exposed in a way we could modify without rolling our own plugin.
The only thing it does not do is replace the unicode character with our SVG icon. This is possible, but it would represent the bulk of the styles, and filtering for the unicode character is one of the few things we can do relatively easily from our WP theme if we desire.
---
@saralohr @mrgerardorodriguez @erikjung @grigs 
See: cloudfour/cloudfour.com-wp#255
> Add vendor styles for Jetpack Markdown footnotes

- src/assets/toolkit/styles/base/base.css
Allows descenders and other glyphs to disrupt underlines.
In @erikjung's original issue describing this problem (#323), he wonders whether or not it makes sense to omit or incorporate the necessary `suitcss-base`/`normalize.css` fixes directly. I commented out `suitcss-base` and noticed numerous regressions, which gave me cold feet. If we think a refactor like that is a good idea, I think it should be tackled as a separate issue.
---
@erikjung @saralohr @mrgerardorodriguez @aileenjeffries 
Fixes #323
> Specify text-decoration-skip property

- src/templates/default.hbs
This is necessary to get the tile image working in Edge. This will also need to be done in WP-land.
See: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101636/
(I don't know why the "after" added it to the top and not the bottom.)
---
@saralohr @mrgerardorodriguez @erikjung 
Fixes #319
> Specify msapplication-config

- src/assets/toolkit/scripts/lib/component/sky.js
- src/assets/toolkit/scripts/lib/core/fn.js
- src/assets/toolkit/scripts/lib/fx/easing.js
- src/templates/default.hbs
#324 
@tylersticka Wanna give this a whirl on your nicely installed IE11 VM?
**TL;DR** There was code using `Map`, which is not transformed by Babel, and is only partially supported by IE11. I'm guessing this was the issue.
/CC @mrgerardorodriguez
> Fix: Replace problematic Map instance with multi-dimensional array

- src/assets/toolkit/styles/components/thumbnail.css
Small change to the `Thumbnail` component to fix some rounding errors in iOS Safari.
I first attempted to solve this by moving the percentage sizing utilities to containing elements, but this was inconsistent (would solve for some sizes and not others). This CSS change seems to fix it everywhere.
---
@saralohr @mrgerardorodriguez @erikjung @aileenjeffries 
Fixes #315
> Inherit border-radius from thumbnail

- src/assets/toolkit/styles/base/base.css
- src/assets/toolkit/styles/components/flex-embed.css
Allows other iframe embeds to continue to manage their own size and aspect ratio.
---
@mrgerardorodriguez @saralohr @erikjung 
Fixes #338 
Related: #285 #281
> Move base iframe styles to FlexEmbed component

- src/assets/toolkit/styles/base/base.css
Makes these links feel a bit more intentional and seamless.
---
@erikjung @saralohr @mrgerardorodriguez 
Fixes #339
> Omit color from a > code

- src/assets/toolkit/scripts/toolkit.js
The `input` event is extremely well-supported. Opera Mini is the only modern browser that doesn’t support it, but `keyup` won’t work as a fallback, so it’s unnecessary. Unlike the `FloatLabel` component, there is no perceivably UX degradation if the event fails to fire.
---
@mrgerardorodriguez @erikjung @saralohr 
Fixes #344
> Remove eventName override for elastic textareas

- src/assets/toolkit/styles/components/table.css
- src/assets/toolkit/styles/utils/index.css
- src/assets/toolkit/styles/utils/scroll.css
- src/patterns/utilities/scroll.hbs
Our technique for overflow scrolling of tables meant tables no longer honored `width: 100%`.
As @saralohr mentioned in her issue (#359), we really only had two options... a container with `overflow-x: auto;` or some sort of modifier on the element itself.
I started by creating a modifier, but the point at which overflow-scrolling should apply seemed entirely dependent on the content. The only good way to do it would be to create breakpoint-specific iterations of the modifier, which seemed like overkill when a single, wrapping utility would serve the same purpose.
---
@saralohr @erikjung @mrgerardorodriguez 
Fixes #359
> Add u-scrollX utility, simplify Table component

- .gitignore
- src/static/images/icons/attachment.svg
This PR removes a duplicate `width` and `height` attribute from the attachment icon, which was making this SVG invalid.
It also adds `.svgsus`' icon set preference file to the `.gitignore`, because that's how I found this issue.
---
@saralohr @nicolemors @erikjung @gerardo-rodriguez
> Fix attachment icon

- src/static/manifest.json
This PR updates the `manifest.json` file as it was [accidentally updated](https://github.com/cloudfour/cloudfour.com-wp/pull/338) in the wrong repo. This adds the GCM Sender ID needed for the web push notifications to work on Chrome.
FWIW, this has happened in the past: https://github.com/cloudfour/cloudfour.com-patterns/pull/325
---
cc: @nicolemors @tylersticka @erikjung
> Update patterns `manifest.json`

- package.json
In the process of working in @nicolemors' work for v2 of the notifications UI, I found that we needed to be running the latest version, `2.0.0`, of the `suitcss-utils-size` dependency. I was having a challenge applying the `u-hidden` class so I dug deeper. As it turns out, [they removed the `display` property from `u-sizeFull` in `2.0.0`](https://github.com/suitcss/utils-size/pull/36) which resolves the problem I was running into. 
In version `1.0.2`, the `u-hidden` styles would be overridden by the `u-sizeFull` styles, which was causing issues.
---
cc: @nicolemors @erikjung @tylersticka
> Update `suitcss-utils-size` dependency

- gulpfile.js
Our Netlify deployments still run on Node 4, so this bit of ES2015 was breaking them.
> Fix: Gulpfile regression

- src/assets/toolkit/styles/base/_config.css
- src/assets/toolkit/styles/components/button.css
- src/patterns/components/button/colors.hbs
Per the suggestion @erikjung made in https://github.com/cloudfour/cloudfour.com-patterns/pull/374#pullrequestreview-9134146, this PR adds a "negative" button modifier.
---
cc: @erikjung
> Feature: Add "negative" button modifier

- src/static/manifest.json
This PR updates the `manifest.json` file to  match the `background_color` used in the [`cloudfour.com-wp` repo](https://github.com/cloudfour/cloudfour.com-wp/blob/master/manifest.json#L18).
Closes #381
> Chore: Update manifest.json

- src/assets/toolkit/styles/components/button.css
This PR allows the `.Button` to have `:--enter`, `:active` states following _existing_ button style setup.
In discussing the [open `Button` PR](https://github.com/cloudfour/cloudfour.com-patterns/pull/380) that has introduced new ideas and a possible refactor of how we style the `Button` pattern, @erikjung and I agreed that at minimum we could make the `.Button` styles have the `:--enter`/`:active` states _without_ needing to add a new modifier. 
The [open `Button` PR](https://github.com/cloudfour/cloudfour.com-patterns/pull/380) will stay open and focus on the possibility of a full `button.css` refactor. 
---
cc: @erikjung @tylersticka @saralohr
> Feature: Refactor button

- src/assets/toolkit/styles/base/base.css
- src/assets/toolkit/styles/base/typography.css
- src/assets/toolkit/styles/components/thumbnail.css
- src/assets/toolkit/styles/sandbox/nm-nav-a.css
- src/assets/toolkit/styles/sandbox/tcs-nav-a.css
- src/assets/toolkit/styles/utils/link.css
The purpose of this was to just unprefix `text-decoration-skip`, but a few other tweaks made it in.
> Tweak: small CSS changes

- src/assets/toolkit/styles/base/_config.css
- src/assets/toolkit/styles/base/base.css
Resolves an issue where `<a>` and `<code>` sometimes failed to meet WCAG 2 AA contrast ratio thresholds.
I chose to create variations of our base color palette variables because changing the root colors caused a pretty dramatic change in appearance, most noticeably to elements that _didn't_ have contrast problems. My hope is by limiting the color changes to dark text only, it'll make the difference imperceptible to the average viewer.
It does not address contrast issues in the following scenarios:
- Orange buttons and message containers with white text. These only fail contrast ratio checks at the smallest sizes, and the only solution appears to be to adopt more of a _brown_ color... no small change to the color made a dent in the warnings. I find this _really_ peculiar... why would …
> Add a11y contrast variations of blue, fuchsia

- src/assets/toolkit/styles/components/icon.css
- src/assets/toolkit/styles/components/message.css
- src/patterns/components/icon/block.hbs
- src/patterns/components/message/overview.hbs
This tweaks the `Message` pattern so that its alignment is consistent as the base `font-size` changes.
There were two reasons this was happening. First, there was whitespace between the `Message-close` element and the SVG within. And second, this problem was worse at some sizes more than others because the icon was being sized as `24px` regardless, but everything around it was changing, which is why some resolutions were more symptomatic than others.
To change this, I borrowed an `Icon--block` modifier technique from our other recent projects so we can piggy-back on the `Icon` class and its built-in sizing logic. Then, I just made `Message-close` use `display: flex;` so its content wouldn't flow as text.
I also fixed some issues I saw with `line-height` and space between the "close" …
> Fix message alignment

- src/assets/toolkit/styles/base/typography.css
- src/assets/toolkit/styles/components/cms-content.css
- src/pages/pages/blog-single-article.hbs
- src/patterns/components/cms-content/base.hbs
- src/patterns/typography/blockquote.hbs
This PR revises our `<blockquote>` pattern in a few ways:
- We retain our fancy citation treatment but now we don't have things like paragraphs running against unordered lists and stuff like that.
- In the `CmsContent` class, the `<blockquote>` element is styled to be more visually offset from adjacent content. This is particularly helpful when it contains elements like `<ul>` that have a similar left padding treatment.
---
@erikjung @gerardo-rodriguez @aileenjeffries @saralohr 
Fixes #362
> Revised blockquotes

- src/assets/toolkit/styles/components/pagination.css
Prevents odd appearances when there are only a few pages visible.
---
@gerardo-rodriguez @aileenjeffries @saralohr 
Fixes #396
> Set flex-basis for Pagination children

- src/assets/toolkit/styles/base/typography.css
- src/assets/toolkit/styles/components/hash-heading.css
- src/assets/toolkit/styles/utils/space.css
- src/pages/pages/blog-single-article.hbs
- src/patterns/components/cms-content/base.hbs
- src/patterns/components/hash-heading/heading-modifiers.hbs
- src/patterns/utilities/space.hbs
This PR lays the groundwork for addressing #363.
It adds a new compliment to the `u-spaceItems*` utilities, `u-staggerItems*`, which does the same thing except with `em` units, which means larger headings will have more `margin-top` than paragraphs or lists. This will improve readability of blog posts without disrupting the rhythm of other content sections.
Unfortunately, this alone wasn't enough. The `HashHeading` component wraps many of the headings, which means most of the headings had the same `1rem` of `margin-top` as they always had. I couldn't change the structure without impacting accessibility, so instead I added optional modifiers for `HashHeading--h1` through `HashHeading--h6`, which sets the appropriate `font` styles so it can be composed proportionally.
---
@erikjung …
> Add HashHeading--h* modifiers, u-staggerItems* utilities

- src/assets/toolkit/styles/vendor/jetpack-markdown.css
Part one of a two-part fix to make this edge case prettier.
---
@erikjung @gerardo-rodriguez @aileenjeffries
> Add hack for making comment footnotes smaller

- src/static/_headers
This is required in order for us to (easily) use the toolkit output on
other sites in conjunction with service workers and caching, etc.
> Add CORS header to allow SW caching

- src/assets/toolkit/styles/components/icon.css
- src/assets/toolkit/styles/components/pagination.css
- src/assets/toolkit/styles/components/sky.css
- src/assets/toolkit/styles/sandbox/sil-pwa.css
- src/pages/sandbox/pwa-stats-single.hbs
- src/pages/sandbox/pwa-stats.hbs
- src/patterns/components/icon/sizes.hbs
- src/patterns/components/pagination/base.hbs
This PR makes changes to three existing components, and refactors the PWA Stats prototypes to use CSS Grid Layout.
I'm doing a PR for this now because I'm still somewhat skittish about adding the PWA Stats specific components to the pattern library proper. They have some idiosyncratic styles that depend on being a child of `.Sky` (or at least a dark background, which is uncommon for the rest of cloudfour.com).
> PWA Stats R2

- src/assets/toolkit/styles/components/sky.css
Helps alleviate visible seam along bottom edge in some browsers.
I haven't tested this on an actual device yet, only via BrowserStack.
---
@grigs @erikjung @gerardo-rodriguez 
See: #417
> Add 1px overlap to repeating clouds

- src/assets/toolkit/styles/components/sky.css
Full explanation in CSS comments.
Only tested in BrowserStack so far.
---
@grigs @erikjung @gerardo-rodriguez 
See: #417 #418
> Cover subpixel seams between skies

- src/assets/toolkit/styles/components/card.css
- src/patterns/components/card/base.hbs
Emphasis elements highlighted in advance of interaction.
> Tweak Card-main text styles

- src/assets/toolkit/styles/components/card.css
> Darken Card meta color for a11y

- src/assets/toolkit/styles/components/footnote-link.css
The purpose of this pull request is to change the design of the footnote links to make them less distracting and not take away from the actual article at hand. They were blue buttons with with white text and it was pretty bold and took the reader out of the article. I played around with different colors and background and came to the grey and black combination. It still says "Hey! Click me!" without being overly distracting.
> Change the style of footnote links to make them less distracting.

- .nvmrc
- src/assets/toolkit/styles/base/_config.css
- src/assets/toolkit/styles/components/button.css
- src/data/colors.yml
- src/pages/sandbox/danielle-buttons.hbs
The existing "primary" and "positive" buttons don't meet WCAG standards for accessibility. To make the “primary” and “positive” buttons accessible, this PR updates several colors including:
- `--color-green`
- `--color-fuchsia`
- `--color-red`
It also adds a new page to the sandbox to test how the new button styles look in use.
> Update Colors and Button Styles

- src/assets/toolkit/styles/base/_config.css
- src/data/colors.yml
- src/static/images/portland.svg
The links in the site footer are not currently accessible. This PR updates `--color-gray` so that the site footer links meet WCAG color contrast standards.
> Update the Color Gray

- src/assets/toolkit/styles/utils/space.css
- src/pages/sandbox/danielle-stagger-headings-a.hbs
- src/pages/sandbox/danielle-stagger-headings-b.hbs
- src/pages/sandbox/danielle-stagger-headings.hbs
- src/patterns/utilities/space.hbs
While we have `u-staggerItems` utilities, sometimes they don't provide enough contrast between  elements. This PR add two new spacing utilities that help to adjust the space between headings and their preceding content:
- `u-staggerHeadings`
- `u-staggerNestedHeadings`
> Add New Spacing Utilities

- src/assets/toolkit/styles/base/_config.css
- src/assets/toolkit/styles/components/button.css
- src/assets/toolkit/styles/components/calendar-date.css
- src/data/colors.yml
As part of #444, we updated the shade of `--color-fuchsia` for accessibility. Unfortunately, this introduced regressions to the contrast accessibility of that color on dark backgrounds, for example in code blocks.
This PR restores the previous value of `--color-fuchsia`, moves the new value to `--color-orchid` (based on the most similar color keyword) and applies either value selectively.
> Differentiate fuchsia variations

- src/assets/toolkit/styles/vendor/prism.css
- src/patterns/components/cms-content/base.hbs
I noticed on some recent blog post drafts that functions had no syntax highlighting in either CSS or JavaScript. This adds that, plus tweaks the green just a tad (since that hue was changed for buttons recently).
> Syntax highlighting tweaks

- package-lock.json
- package.json
- src/assets/drizzle/styles/base/use.css
This PR fixes #436 by making the Drizzle CSS use Preset Env instead of the now-defunct cssnext.
> Use Preset Env for Drizzle styles

- .storybook/preview.js
- .storybook/preview.scss
- package-lock.json
- package.json
- src/base/_defaults.scss
- src/base/_index.scss
- src/base/_typography.scss
- src/demo/button/button.stories.mdx
This PR adds some initial base/reset/normalize styles to the project. It then includes these in every Storybook preview via [a preview configuration file](https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78). This file also allowed me to simplify configuration of global decorators, specifically the a11y add-on.
After implementing these base styles, I noticed that all of the examples were running up against the edge of their container. I decided to install the extremely popular [centered add-on](https://github.com/storybookjs/storybook/tree/master/addons/centered), but if we dislike it we can use the `preview.scss` file to further customize however we wish.
Either locally or at the deploy preview URL:
1. Inspect any of the demo elements and confirm that its …
> Add initial base styles

- browserslist
If we are going to have workarounds to support Safari 10, we should also ensure that autoprefixer generates prefixes compatible with Safari 10 and that postcss-preset-env emits syntax compatible with Safari 10
> Add Safari 10 to browserslist

- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- package.json
This adds the "Backgrounds" add-on for Storybook. This allows us to swap the preview canvas's background for one of those in our color palette. We can also re-run accessibility tests once a background is applied.
I reached a point where I would find this useful while working on #475.
> Add choosable backgrounds

- src/base/_fonts.scss
- src/base/_typography.scss
- src/demo/button/button.scss
Fixes lint errors introduced between #506 and #507 being merged.
Verify status checks pass.
> Fix lint errors

- README.md
- gulpfile.js/index.js
- gulpfile.js/tasks/svg-to-twig.js
- package-lock.json
- package.json
I was experimenting with a tweak that would require another Gulp task, and I realized how quickly a gulpfile can spiral into crazy-ness when lots of unrelated stuff is housed in the same file. It also makes it challenging to tell which dependencies are required for which functionality.
This PR gets ahead of that by moving `gulpfile.js` to `gulpfile.js/index.js`. It then exports everything from `gulpfile.js/tasks/` using [require-dir](https://www.npmjs.com/package/require-dir).
1. Confirm deploy checks all pass
> Separate gulp tasks

- src/design-tokens/colors.yml
- src/design/colors.stories.mdx
Now that design token documentation is automated, I've moved some of the accessibility notes into the tokens. This also allowed me to simplify some of the _design_ docs to show the palette gradations together, something @dromo77 and I had discussed but previously avoided because it made it harder to refer to individual variable names (which is no longer a concern since tokens are documented separately).
Design/Colors docs consolidate palette colors:
Design Tokens/Colors docs include accessibility info:
> Color token and doc tweaks

- src/base/_typography.scss
- src/mixins/_fluid.scss
Our current site adapts the base `font-size` above a certain breakpoint, which is good. Instead of adjusting every single type size, you apply a larger base at the root and then adjust anything else as needed.
But the current version has a hard `2px` increase at a single pre-defined breakpoint. That means there are a lot of sizes where the type feels somewhat unaddressed.
While I personally kind of like responsive font sizes to be "unchained," a lot of readers and designers prefer some sort of cap.
The most popular technique for this is [Bootstrap's RFS engine](https://github.com/twbs/rfs). I decided against this for a few reasons:
- I find its "maximum size first" approach counter-intuitive.
- Its documentation seems to encourage using it in a _lot_ of places, which sort of invalidates a …
> Fluid responsive type lock

- renovate.json
Currently we are using prettier versions directly from GitHub, because they haven't released a version yet that includes bugfixes we need. Since there are very frequently commits to the prettier repo, renovate would try to update this all the time, which would become annoying. This PR switches it so that renovate only checks for prettier updates once a month.
When prettier releases a new version, we can switch to that version, and remove this section from the renovate config.
> Only update prettier commit hash monthly

- .remarkrc.js
- .storybook/cloud-four-theme.js
- .storybook/main.js
- .storybook/manager.js
- .storybook/theo-importer.js
- .storybook/theo-loader.js
- gulpfile.js/tasks/svg-to-twig.js
- gulpfile.js/tasks/theo-to-mdx.js
- gulpfile.js/tasks/watch.js
- gulpfile.js/theo-formats/stories.mdx.js
- package-lock.json
- package.json
- renovate.json
- src/components/button/button.stories.mdx
- src/components/table/table.stories.mdx
- src/design/colors.stories.mdx
- src/design/icons.stories.mdx
- src/design/typography/typography.stories.mdx
Switches prettier from using the version from `master` on GitHub to the latest `v2`. We were using the version from `master` because it had a MDX fix that we needed that not had been published yet. But now they have published a new version so that is no longer necessary.
> Update prettier to v2

- src/assets/icons/check.svg
- src/components/checkbox/checkbox.scss
- src/components/checkbox/checkbox.stories.mdx
- src/components/checkbox/checkbox.twig
- src/components/checkbox/demo/styles.scss
- src/components/checkbox/demo/with-label.twig
- src/components/input/input.stories.mdx
- src/components/input/input.twig
- src/design-tokens/sizes.yml
Adds a `c-checkbox` class intended for `<input type="checkbox">` elements.
Originally I was going to style `radio` inputs as well, but I noticed we have _never_ used those on our current site, and it increased the size of the CSS enough that I thought it seemed off. I've also always struggled with naming a single class for both use cases… if we eventually add `c-radio`, [mixins might be a more performant solution](https://csswizardry.com/2016/02/mixins-better-for-performance/) anyway.
I originally had `checked` as a Storybook knob, but I decided to remove it because manipulating the property via Storybook does not animate. I'd rather devs click the element to see the animation.
1. Try out Checkbox component in deploy preview.
---
- See #490 
- Resolves #461
> Checkbox component

- src/components/table/table.scss
> After #573 was merged, tables started expanding to fill their available width. When that happened, it became more clear that the current alignment of table headings feels a bit off with numeric data.
I updated the numeric modifier to right-align all the whole table.
This fixes the alignment issue while keeping it easy to override.
1. Review tables for regressions
---
- Fixes #577
> Fix numeric heading drift

- .storybook/preview.js
- .storybook/preview.scss
- src/components/button/button.stories.mdx
- src/components/checkbox/checkbox.stories.mdx
- src/components/icon/icon.stories.mdx
- src/components/input/input.stories.mdx
- src/components/table/table.stories.mdx
- src/design/typography/typography.stories.mdx
- src/index.scss
- src/objects/container/container.stories.mdx
- src/themes/_index.scss
- src/themes/themes.stories.mdx
- Only outputs project styles once.
- Makes sure all relevant project styles are included in consumable CSS.
- Remove demo CSS from consumable CSS.
While attempting to create a Prototypes section (as per this afternoon's design conversation), I ran into some issues related to limiting demo CSS to individual stories. While troubleshooting _that_, I was confused by a whole _pile_ of `<style>` elements in the `<head>`. I then realized that every time we ran `import` on an SCSS file, that would output that CSS to the `<head>` of every single story. This meant there was a lot of duplicate styles in our `<head>`.
This attempts to simplify by instead importing the global CSS _once_ (in `preview.js`). This has the added benefit of no longer requiring `import` of SCSS files in individual stories. …
> Fix duplicate CSS output

- renovate.json
Closes #613. Removes assignees and adds `team:` prefix to `reviewers`
> Update renovate.json reviewers

- package.json
Remove the `private` flag from `package.json` so we can publish this package to the npm registry.
> Remove Private Flag

- .theo/formats/stories.mdx.js
Makes several improvements to our Theo design token translation task:
- If any token in a category includes comments, they will be displayed in a new "comment" column.
- If a token is in category `font-family`, the value will have each step of the stack applied for preview purposes.
- All token names and non-font-family token values are wrapped in `<code>` so they are more consistent line to line.
> Show token comments and font families in docs

- .storybook/preview.js
Makes three changes to our integration of [the viewports addon](https://github.com/storybookjs/storybook/tree/master/addons/viewport):
- Changes our breakpoint heights to account for the UI padding and border. Previously, applying one of these breakpoints would result in an extra scrollbar.
- Fixes a typo in our breakpoint token names (`breakpoints` → `breakpoint`)
- Swaps `MINIMAL_VIEWPORTS` (which contained opinionated approximations of categories we tend to discourage, for example "Tablet") with `INITIAL_VIEWPORTS` (which includes specific devices, which are not as subjective).
> Adjust viewport settings

- src/design-tokens/modular-scale.yml
- src/design/modular-scale.stories.mdx
While working on revised whitespace patterns it occurred to me that their documentation could be simplified by introducing a shared page describing our modular scale. This PR introduces that on its own to simplify future PRs.
I also defined the minimum and maximum steps of our scales as design tokens. This will come in handy when it comes time to generate utility classes for these steps.
> Add modular scale documentation

- src/utilities/spacing/demo/directions.twig
- src/utilities/spacing/demo/logical-properties.twig
- src/utilities/spacing/demo/styles.scss
- src/utilities/spacing/spacing.scss
- src/utilities/spacing/spacing.stories.mdx
This reintroduces spacing utilities to the project with the following changes from the production version:
- New class naming convention.
- Retains step `0` instead of omitting it.
- Does not reintroduce `space-items` (see #644).
- Uses logical property names instead of physical ones.
- Uses relative units (`em`).
This PR does not include responsive variations of these utilities because it was getting a little large as-is.
Logical property support varies between browsers. This should be resolved by #646. For now, it's best to test in Firefox.
> Spacing utilities

- .browserslistrc
If a project dependent on this project wants to support more browsers than this, they can add their own build process to compile to their own browser targets.
PR created based on this discussion: https://github.com/cloudfour/cloudfour.com-patterns/pull/652#discussion_r414910782
New browsers list is (from `npx browserslist`):
```
and_chr 79
and_uc 12.12
chrome 79
firefox 72
ios_saf 13.3
ios_saf 13.2
safari 13
samsung 10.1
```
🤷 run `npx browserslist` and make sure there are no unexpected browsers?
> Only support widely used modern browsers

- .prettierignore
Previously, if you ran:
```
npm run preprocess
npm run check-lint
```
It would say that `src/design-tokens/generated/font.stories.mdx` did not match prettier format
Now, prettier ignores those generated files.
Checkout this branch, run the above commands, ensure it has exit code 0
Closes #654
> Add generated design tokens to .prettierignore

- src/utilities/list/demo/style-type.twig
- src/utilities/list/list.scss
- src/utilities/list/list.stories.mdx
Another utility a different pattern would benefit from.
Our current pattern is `u-list-reset`, which sets both `list-style: none` and `padding-left: 0`. What's awkward about this currently is that `padding-left` does not have `!important` set, because if it did, you wouldn't be able to set your own padding while also omitting bullets from a list element.
I decided that felt a bit silly, so in this case I've borrowed another concept [from Tailwind](https://tailwindcss.com/docs/list-style-type) and limited this type of utility to a style type override. This means to truly reset a list via utilities alone you'll need something like `u-list-none u-pad-none`, but I think that may actually be easier to understand and troubleshoot.
---
- See #492
> Add u-list-none utility

- src/mixins/_a11y.scss
- src/utilities/display/demo/hidden-visually.twig
- src/utilities/display/display.scss
- src/utilities/display/display.stories.mdx
Adds `u-hidden-visually` utility, which I wanted for a different pattern.
This is mostly the same as [what we have currently](https://cloudfour-patterns.netlify.app/patterns/utilities.html#display). I kept the `hidden` past-tense because I like the consistency with `visibility: hidden`, `aria-hidden`, the `hidden` attribute, etc.
The only differences are:
- New class name based on our latest standards.
- Very slightly updated styles based on @Paul-Hebert's [article on the subject](https://cloudfour.com/thinks/see-no-evil-hidden-content-and-accessibility/#showing-additional-content-for-screen-readers).
- Styles are applied via a mixin, in case any of our component elements would benefit from these same styles.
1. View deploy preview.
1. Navigate to the Utilities ▸ Display ▸ Hidden Visually …
> Add u-hidden-visually utility

- src/base/_defaults.scss
- src/design-tokens/sizes.yml
- src/design/typography/demo/inline-elements.twig
- src/themes/_dark.scss
We noticed in an article draft recently that we weren't providing any real styling for the `<kbd>` element, which represents keyboard commands. I started by extending our existing `<code>` styles to that element, but decided it might be fun to add just a _pinch_ of skeuomorphism and make them look like keys. I tried not to _overdo_ it, because I wanted it to be clear that they are not _buttons_.
Note that Storybook's Accessibility tab will raise one "incomplete" test for the "command" (`⌘`) keyboard example since it has no text variation. The usual ways around this did not work for me. I decided to keep it as I couldn't find any accessibility information specific to `kbd`, and I think it's a good example of the pattern's usage, but I'm open to feedback on that.
I also noticed a failing …
> Add kbd style

- src/components/sky-nav/sky-nav.stories.mdx
- src/components/sky-nav/sky-nav.twig
I'm extremely proud of the accessibility knowledge in this team. Although the accessibility challenges of our site pale in comparison to those of our main projects, I see that as an invitation to poke a bit at the underpinnings of what we're doing.
Case-in-point: A primary navigation PR consisting _only_ of markup! Well, markup and a pinch of Twig template tags.
I based this revised markup structure on a recent client project with a couple of small changes. Here's a summary of everything that's changed from our what's on our live site:
- Moved the "skip to main content" link _out_ of the `<header>`, since that's where [Heydon](https://heydonworks.com/latest/) seems to put it on all of his projects.
- Replaced the menu button with an actual `button` element, and updated its fallback text …
> Primary navigation markup

- package.json
- renovate.json
This PR is created with the hopes that merging it will prevent renovate from making PR's like this: https://github.com/cloudfour/cloudfour.com-patterns/pull/685 and this: https://github.com/cloudfour/cloudfour.com-patterns/pull/680 (for the node version)
The `engines` field is how we specify which node versions we allow our package consumers to use. If that version is pinned, then that means that we are telling our package consumers that they must use node 14.2.0 only, but node releases new versions really frequently so that would be really annoying.
I don't know if these configuration changes will do what we want, but we can't really test it until we merge this. It was my best-guess of what would work based on these documentation pages:
- …
> Change how renovate handles node versions

- README.md
This commit adds a link to the contributing guide from the readme, which I forgot to add when I relocated those instructions to a new file.
Fixes #702
> Link to CONTRIBUTING from README

- src/components/pagination/pagination.scss
Updates the SVG inline color assignment for `c-pagination` to account for `currentColor` being unnecessary now. This renders the arrows visible again.
1. View deploy preview.
1. Confirm arrows are visible when next/back affordances are visible.
1. Confirm the same when dark theme is active.
---
- Fixes #706
> Fix pagination arrows

- .storybook/preview.js
- src/design/icons/icons.stories.mdx
- src/vendor/wordpress/gutenberg.stories.mdx
See issue #709
This PR consolidates our vendor specific stories and source files into a commonly named `vendor/` directory. 
Storybook organization:
Source file organization:
In #704 I also renamed an icon section "Third-party Icons". It felt appropriate to revisit that with this PR as well. 
1. Confirm that this direction/organization is not fubar
1. Review files changed
1. View [theme deploy](https://deploy-preview-719--cloudfour-patterns.netlify.app/) and check Storybook and make sure Gutenberg stories work as expected. 
---
Also related to #710
> Chore: reorganizes third-party assets into vendors directory

- renovate.json
Tries to disable PR's like this: https://github.com/cloudfour/cloudfour.com-patterns/pull/690
I think this is the config we want: https://github.com/renovatebot/config-help/issues/81#issuecomment-414104278
> Disable renovating node version

- package-lock.json
- package.json
- src/vendor/prism/_theme.scss
- src/vendor/prism/config.js
- src/vendor/prism/demo/samples/bash.txt
- src/vendor/prism/demo/samples/css.css
- src/vendor/prism/demo/samples/jsx.jsx
- src/vendor/prism/demo/samples/liquid.liquid
- src/vendor/prism/demo/samples/php.txt
- src/vendor/prism/demo/samples/toml.txt
- src/vendor/prism/demo/samples/tsx.tsx
- src/vendor/prism/demo/samples/twig.txt
- src/vendor/prism/demo/samples/typescript.ts
- src/vendor/prism/demo/samples/yaml.txt
- src/vendor/prism/globals.ts
- src/vendor/prism/prism.stories.mdx
This PR updates our Prism configuration and our syntax highlighting theme to accommodate the following new languages:
- Bash, Shell
- Liquid
- React JSX
- React TSX
- TOML
- Twig
- TypeScript
- YAML
To keep the theme lean and to maintain a loose consistency between color-logic associations between languages (which I feel is helpful when reading an article involving multiple languages, such as JavaScript and CSS), I chose to comment out my original theme and to pepper the styles back in, making adjustments based on how it impacted _all_ examples unless an override was absolutely necessary. Only 11 more lines of CSS to double our language support!
One side effect is that the theme design _has_ changed a tad, which is why I'm requesting design review in addition to developer review.
[View …
> Support more highlighted languages

- src/components/heading/heading.twig
- src/components/icon/demo/basic.twig
- src/components/icon/demo/inline.twig
- src/components/icon/icon.stories.mdx
- src/components/icon/icon.twig
- src/components/message/message.twig
- src/design/icons/icons.stories.mdx
- src/objects/rhythm/demo/article.twig
- src/objects/rhythm/demo/summary.twig
- src/utilities/display/demo/hidden-visually.twig
Now that dynamic template paths are supported, we no longer have to avoid a component template for `c-icon`. Hooray!
---
- Resolves #758
> Icon component template

- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- package.json
Adds [a Storybook add-on](https://github.com/whitespace-se/storybook-addon-html) that displays the output HTML of the current canvas in its own tab. This is presumably a stop-gap solution until Storybook 6's more versatile storysource add-on is done.
> Add HTML tab to Storybook canvas

- src/components/calendar-date/calendar-date.twig
I noticed while working on #769 that our Calendar Date component's note container was being output even when the note had no content. This resolves that.
1. View the HTML tab of the Basic canvas [in `v-next`](https://v-next--cloudfour-patterns.netlify.app/?path=/story/components-calendar-date--basic) and in [the deploy preview](https://deploy-preview-770--cloudfour-patterns.netlify.app/?path=/story/components-calendar-date--basic). Confirm that the `c-calendar-date__note` element is gone in the deploy preview.
1. Confirm that the note is still visible in [the "With Note" example](https://deploy-preview-770--cloudfour-patterns.netlify.app/?path=/story/components-calendar-date--with-note).
> Only output calendar date note when there is one

- .changeset/few-parrots-draw.md
- package-lock.json
- package.json
- src/vendor/wordpress/gutenberg.stories.mdx
So far, we have not been including the WordPress default styles for Gutenberg block elements in Storybook. This PR imports the missing stylesheet into our Gutenberg story documentation. 
Observe the before and after presentation of various block elements
**Before:** 
**After:** 
**Before:**
**After:** 
After installing `@wordpress/block-library` via NPM I observed these security audits in my terminal:
I assumed the Renovate bot would address these so no action was taken in this PR. 
1. Compare the Gutenberg stories in the [master branch](https://v-next--cloudfour-patterns.netlify.app/?path=/docs/vendor-wordpress-gutenberg--core-audio) to the same blocks in the [deploy preview](https://deploy-preview-778--cloudfour-patterns.netlify.app/) for this PR. 
---
See: …
> Chore: imports WordPress block-library styles

- .eslintignore
- .prettierignore
This commit adds `/ts-dist` to both the Prettier and ESLint ignore lists, to avoid lint failures for generated files.
1. run `npm run type` (to generate the `ts-dist` folder)
1. run `npm run check-lint`
There should be no lint failures.
> Ignore /ts-dist folder

- CONTRIBUTING.md
This PR adds a quick note to the Contributing Guide that running tests
depends on having built the project.
> Add Testing Note to Contributing Guide

- renovate.json
https://docs.renovatebot.com/configuration-options/#suppress-branchpr-creation-for-x-days
I didn't realize this setting was necessary. If this setting had been set, [this PR](https://github.com/cloudfour/cloudfour.com-patterns/pull/964) wouldn't have been opened yet.
> Change renovate to not create PR's until after stabilityDays

- .changeset/cuddly-kids-taste.md
- .storybook/main.js
- src/design/icons/icons.stories.mdx
I started making an unrelated change to a pattern, but on every save I saw errors about SVG loading in the Terminal. These appear to be uncaught issues with changes from #862, which caused the icon listing to fail (which explains its disappearance from [our deploy](https://v-next--cloudfour-patterns.netlify.app/)).
I tried a few different solutions, but there were three points of Webpack configuration around `.svg` files and whenever I fixed _one_ a different one would have issues.
I looked back at the history of _why_ there was so much SVG configuration, and realized it was all due to #503, specifically the need to convert SVG files to React components for the sole purpose of documentation.
Since that's the _only_ context where we'd want to do that, I decided to use inline loaders within …
> Only use svgr in specific contexts

- .changeset/green-grapes-unite.md
- gulpfile.js/tasks/build-sass.js
No inlined SVGs in CSS files were included in the output CSS. This is because we weren't running PostCSS outside of Webpack except for minification.
This adds PostCSS as a step in our `buildSass` task.
1. Observe [the latest version of `standalone.css`](https://unpkg.com/@cloudfour/patterns@0.3.0/dist/standalone.css), confirm that it includes uncompiled `svg-load()` functions in its output (which it should not).
1. Check out branch locally.
1. Run `npm run build:sass`
1. Confirm that `dist/standalone.css` and `dist/standalone.min.css` include `url("data:image/svg+xml;...")` strings instead of `svg-load()` functions.
> Run PostCSS in buildSass

- .changeset/selfish-moons-whisper.md
- CONTRIBUTING.md
- src/components/pagination/pagination.twig
It's possible in WordPress or Timber through certain configurations to output pagination items without any links, for example a "…" item preceding a jump to the very last page number. This PR prevents those actions from outputting empty links anyway.
Review [the pagination component in the deploy preview](https://deploy-preview-1005--cloudfour-patterns.netlify.app/?path=/story/components-pagination--example). It should work the same as before.
> Support non-link pagination items

- .github/workflows/ci.yml
Here is the failure: https://github.com/cloudfour/cloudfour.com-patterns/runs/1408782567
https://github.com/cypress-io/github-action/issues/229
👀 The `test` action passed ✅
> Upgrade Cypress GH action to fix failed build

- .changeset/polite-rings-taste.md
- src/objects/container/container.twig
The container object included a separate `theme` property in addition to `class`. Unfortunately this property conflicts with the `theme` property in Timber templates, which is not a string and causes errors. While these are resolvable by passing `only` to the include or embed, since this is the only pattern we had that included this property it seemed simpler to remove it.
> Remove theme property from container object

- .changeset/wicked-experts-listen.md
- src/base/_defaults.scss
- src/objects/page/demo/example.twig
- src/objects/page/page.scss
- src/objects/page/page.stories.mdx
- src/objects/page/page.twig
Adds an `o-page` object for defining the main page content versus the footer content, which allows the footer to "stick" to the bottom of the viewport on shorter pages.
Storybook injects some HTML that works against the demo, but I think I figured out how to override it for this example via `useEffect`.
I chose to use CSS Grid because it required less CSS. I think it's fine if this doesn't work in unsupported browsers, it just means the footer will directly follow the content (as it does today).
---
- Fixes #742
> Page object

- .changeset/real-comics-play.md
- src/components/ground-nav/ground-nav.scss
- src/components/ground-nav/ground-nav.twig
The Ground Nav pattern was built before we had standard container padding, which change depending on breakpoint. This updates that pattern to use the standard container padding where possible to promote alignment with adjacent content sections.
The main visual changes are to horizontal padding for the top ("action") and bottom ("content") sections, and vertical padding for the bottom section. Vertical padding for the top section is unchanged to avoid disrupting the composition of the illustration relative to the call to action.
---
/CC @dromo77
> Use container padding where possible in Ground Nav

- src/components/card/card.scss
- src/mixins/_embed.scss
- src/mixins/_media-query.scss
I've been working on a new layout pattern with breakpoint modifiers and I found myself growing a bit tired of typing the same breakpoint class logic over and over. At one point I accidentally mismatched a breakpoint class name with its value (I typed `\@l` but I was still using `breakpoint.$m`) and decided it was time to make a robot do that busy work.
So this PR introduces a new `mixins/_media-query.scss` module. You can see the source for details, but the two most important mixins are `breakpoint-classes` and `breakpoint-parent-classes`.
```scss
@use 'path/to/design-tokens/breakpoint.yml';
.example--red {
color: red;
}
.example--red\@m {
@media (width >= breakpoint.$m) {
color: red;
}
}
.example--red\@l {
@media (width >= breakpoint.$l) {
color: red;
}
}
.example__child {
color: blue; …
```
> Add breakpoint helper mixins

- .changeset/eight-jokes-report.md
- src/components/event-log/demo/events.json
- src/components/event-log/demo/events.twig
- src/components/event-log/event-log.scss
- src/components/event-log/event-log.stories.mdx
- src/components/event-log/event-log.twig
- src/components/event-log/item.twig
- src/design-tokens/sizes.yml
- src/objects/list/list.scss
- src/objects/media/media.scss
- src/vendor/wordpress/_wordpress.scss
> Displays a list of event details in chronological order. Designed to show the presentation history for talks, workshops or other events we’ve conducted.
Improvements from the existing site's pattern ([visible lower on this page](https://cloudfour.com/presents/why-you-should-build-a-progressive-web-app-now/)):
1. Each item has a heading element, which makes them easier to navigate with screen readers.
1. Each date is a `<time>` element, which adds semantic meaning.
1. Uses [Subgrid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid) in supported ~browsers~ [browser](https://caniuse.com/css-subgrid) ([Microsoft is reported to be adding Chromium support](https://blog.chromium.org/2020/06/improving-chromiums-browser.html), though, so 🤞)
1. No need to manually add …
> Component: Event Log

- .changeset/unlucky-colts-serve.md
- src/components/card/card.scss
- src/components/card/card.stories.mdx
- src/design-tokens/sizes.yml
- src/objects/deck/deck.scss
- src/objects/deck/deck.stories.mdx
- src/objects/deck/deck.twig
- src/objects/deck/demo/articles.json
- src/objects/deck/demo/articles.twig
Adds a layout object intended for displaying a grid of card components. By default, columns are created automatically, but they can be explicitly defined from a particular breakpoint. Horizontal cards will automatically span all available columns.
I am open to alternative names. See Docs and CSS comments for more info.
1. Proofread [docs for new object](https://deploy-preview-1075--cloudfour-patterns.netlify.app/?path=/docs/objects-deck--basic)
1. Try out [canvas view](https://deploy-preview-1075--cloudfour-patterns.netlify.app/?path=/story/objects-deck--horizontal-card), play with controls
> Object: Deck

- .storybook/main.js
- package-lock.json
- package.json
Adds [Storybook Mobile](https://medium.com/storybookjs/storybook-mobile-6c654d44fc64), which compliments our existing Accessibility add-on by showing hints and warnings for things like missing `srcset`, `autocomplete` attributes and mobile-specific usability concerns.
I also took this opportunity to re-arrange the add-ons slightly so that "Controls" were always first (since that's the most actionable tab), followed by Accessibility and Mobile.
Click around [the deploy preview](https://deploy-preview-1076--cloudfour-patterns.netlify.app/) in "canvas" view with the "Mobile" tab open.
---
Thanks @spaceninja for showing me this add-on!
> Add Storybook Mobile

- .changeset/serious-candles-cough.md
- package.json
This PR adds our compiled design tokens to the npm package output for
consumption in the WordPress theme.
To the best of my knowledge, there's no way to test this without publishing the package, which I can't do until this PR is merged. That said, the change is really simple, and I'm confident in it.
---
- Fixes #1095
> Expose Design Tokens in npm Package

- .storybook/preview.js
Storybook's sorting options are now very simple. This updates our configuration to take advantage of this, to remove "Design Tokens" (since that's no longer top-level), and to preemptively add a few potential future categories just to make our lives easier.
> Simplify Storybook sorting

- .storybook/main.js
- package-lock.json
- package.json
Here is the warning that I was seeing:
```
(node:72580) DeprecationWarning: Relying on the implicit PostCSS loader is deprecated and will be removed in Storybook 7.0.
If you need PostCSS, include '@storybook/addon-postcss' in your '.storybook/main.js' file.
See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader for details
```
It was an easy fix so I thought I'd knock it out.
I compared `http://localhost:6006/main.css` before and after this change, and there were no changes ✅
> Fix storybook implicit postcss deprecation warning

- .changeset/metal-ways-thank.md
- src/components/avatar/avatar.stories.mdx
- src/components/button/button.stories.mdx
- src/components/card/card.stories.mdx
- src/components/checkbox/checkbox.stories.mdx
- src/components/cloud-cover/cloud-cover.stories.mdx
- src/components/dot-leader/dot-leader.stories.mdx
- src/components/event-log/event-log.stories.mdx
- src/components/ground-nav/ground-nav.stories.mdx
- src/components/heading/heading.stories.mdx
- src/components/icon/icon.stories.mdx
- src/components/input/input.stories.mdx
- src/components/pagination/pagination.stories.mdx
- src/components/sky-nav/sky-nav.stories.mdx
- src/design/colors.stories.mdx
- src/design/fallback-images/fallback-images.stories.mdx
- src/design/icons/icons.stories.mdx
- src/design/modular-scale.stories.mdx
- src/design/typography/typography.stories.mdx
- src/objects/bunch/bunch.stories.mdx
- src/objects/container/container.stories.mdx
- src/objects/deck/deck.stories.mdx
- src/objects/embed/embed.stories.mdx
- src/objects/media/media.stories.mdx
- src/utilities/rounded/rounded.stories.mdx
- src/utilities/spacing/spacing.stories.mdx
- src/vendor/wordpress/gutenberg.stories.mdx
This fixes broken links in the documentation.
Before: https://v-next--cloudfour-patterns.netlify.app/
After: https://deploy-preview-1248--cloudfour-patterns.netlify.app/
1. Browse around and confirm links are working
---
- Closes #1247
> Fix broken documentation links

- .changeset/rude-singers-hope.md
- src/objects/bunch/bunch.scss
Sets `z-index: 0` on `.o-bunch` so its children won't display beneath outside elements in Chrome.
[Test `o-bunch` in deploy preview](https://deploy-preview-1255--cloudfour-patterns.netlify.app/?path=/docs/objects-bunch--of-avatars#bunch)
---
- Fixes #1243
> Make sure a fresh z-index is set for o-bunch

- .storybook/preview.js
- package-lock.json
- package.json
Storybook's kind of weird. It seems to use tree-shaking to dynamically include highlight language definitions for doc blocks, but not for code blocks specified via Markdown. Thankfully, they're using a well-documented library for code definitions, so I was able to extend that from our `preview.js`.
With this change, any Twig blocks in our docs should receive syntax highlighting.
Before:
After:
Try adding a Markdown code block with the language `twig` to any `.stories.mdx` file.
---
- Related to #1004 and #1240
/CC @gerardo-rodriguez
> Support Twig highlights in Storybook

- src/components/cloud-cover/cloud-cover.stories.mdx
- src/components/ground-nav/ground-nav.stories.mdx
- src/objects/container/container.stories.mdx
- src/objects/page/page.stories.mdx
- src/prototypes/articles/articles.stories.js
- src/prototypes/card-variations/card-variations.stories.js
- src/prototypes/cloud-divider/clouds.stories.js
- src/prototypes/comment-thread/thread.stories.js
I noticed while reviewing #1259 that the `paddings.disabled` attribute wasn't working. Then I noticed it had stopped working on several stories.
It looks like [the add-on we're using](https://github.com/rbardini/storybook-addon-paddings) updated the property at some point (which is more consistent with other add-ons now), so this PR updates the property key accordingly. 
View affected stories on deploy preview, confirm that in canvas view they have no additional padding visible (meet the edge of the canvas).
> paddings.disabled → paddings.disable

- .changeset/slimy-clocks-laugh.md
- src/vendor/wordpress/_wordpress.scss
Applies `alignfull` and `alignwide` to any `wp-block-*` class.
Confirm that alignment control of [Gutenberg image story](https://deploy-preview-1284--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-gutenberg--core-image) still functions as it did before.
---
- Fixes #1270
> Broaden reach of alignment classes

- .changeset/swift-avocados-worry.md
- src/components/card/card.scss
- src/components/card/card.stories.mdx
- src/design/demo/theme.twig
- src/mixins/_theme.scss
- src/tokens/size/border.json
- Adds `c-card--contained` modifier, giving cards distinct boundaries to offset them from their containing element.
- Adds an `unthemed-styles` mixin to define styles that should apply only when a theme class is not directly attached to the element.
This PR does _not_ include the distinctly separated footer from the rest of the card contents. I realized partway into this task that making this happen would represent 95% of the effort, but that design detail is only present on PWA Stats. Because there's another issue blocked by this and many more directly related to our short-term goals, it felt odd to spend many more hours (if not days) refactoring for this design detail we wouldn't use right away. I plan to create another issue to address that detail at a later date.
[Deploy …
> Add c-card--contained modifier

- .changeset/hot-bees-relate.md
- src/components/card/card.scss
- src/tokens/size/border.json
- src/vendor/wordpress/_wordpress.scss
This PR adds a border-radius to the Gutenberg Group styles when `has-background` class is present.
1. [Deploy link](https://deploy-preview-1297--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-gutenberg--core-group)
---
- Fixes https://github.com/cloudfour/cloudfour.com-patterns/issues/1269
> Gutenberg corners

- .changeset/giant-keys-look.md
- .style-dictionary/config.js
We've found a use case for consuming these tokens via PHP. Since PHP, like most server-side languages, has built in [JSON support](https://www.php.net/manual/en/book.json.php), the easiest way to do this is to expose a JSON format of tokens using Style Dictionary's existing format. I chose the [`json/nested`](https://amzn.github.io/style-dictionary/#/formats?id=jsonnested) format so the file would maintain its hierarchy without requiring `.value` calls.
Run `npm run build` and confirm that `src/compiled/tokens/json/tokens.json`  is populated with our tokens in JSON format.
> Export tokens as nested JSON

- .changeset/hungry-mirrors-visit.md
- src/vendor/wordpress/_wordpress.scss
- src/vendor/wordpress/gutenberg.stories.mdx
- Simplifies the spacing for `wp-button-blocks`. This is a less sophisticated solution but it doesn't require knowledge of which `o-rhythm` modifier is in use anymore, and I think it's fine for buttons located within prose content.
- Only applies adjacent button spacing to `wp-button-block` when it is nested within `wp-button-blocks`. Before, lone buttons would appear to have extra padding since they expected to always be contained.
[Deploy preview](https://deploy-preview-1311--cloudfour-patterns.netlify.app/?path=/docs/vendor-wordpress-gutenberg--core-buttons#button)
---
- Fixes #1310
> Fix extra padding on single Gutenberg button

- src/components/calendar-date/calendar-date.stories.mdx
This PR updates one of the code examples + adds documentation of the template props and block.
Left: Before
Right: After
1. Review https://deploy-preview-1313--cloudfour-patterns.netlify.app/?path=/docs/components-calendar-date--basic
---
- See #1289
> Add Calendar Date code example + template props/block docs

- .changeset/serious-clocks-visit.md
- .changeset/silver-dodos-turn.md
- src/components/author/author.stories.mdx
- src/components/author/author.twig
This PR updates the Author component to not explicitly call functions for the properties.
Left: Before
Right: After
1. Review https://deploy-preview-1300--cloudfour-patterns.netlify.app/?path=/docs/components-author--default-story
2. Confirm no regressions
---
- See #1289
> Make the Author story code example better/update component

- src/components/card/card.stories.mdx
This PR updates the Card component documentation by refining the code examples. A "Template Properties" and "Template Blocks" section was also added.
Left: Before
Right: After
Preview: https://deploy-preview-1315--cloudfour-patterns.netlify.app/?path=/docs/components-card--content-blocks
1. Review all code examples and confirm they are accurate.
2. Review the "Template Properties" and "Template Blocks" sections and confirm they are accurate.
---
- See #1289
> Update Card component documentation

- src/components/calendar-date/calendar-date.stories.mdx
This PR refines the code example for the Calendar Date component Seasons example.
Left: Before
Right: After
1. Review the Calendar Date Seasons code example
---
- See #1289
> Refine Calendar Date Seasons code example

- .storybook/preview.js
One of our Storybook add-ons published a minor version release, which Renovate automatically updated: #1328
This version of the add-on streamlined its implementation, no longer requiring a decorator function. Unfortunately because the decorator was removed entirely, every single story after this update showed a `fn is undefined` error.
This PR removes the decorator, resolving the error.
1. Review [deploy preview](https://deploy-preview-1332--cloudfour-patterns.netlify.app/), confirm that stories are once again visible.
2. In Canvas view, confirm that the paddings dropdown still functions.
> Remove withPaddings decorator

- .changeset/fast-mugs-itch.md
- .changeset/olive-berries-watch.md
- .changeset/two-ghosts-punch.md
- .changeset/violet-schools-mix.md
- .style-dictionary/build.js
- .style-dictionary/config.js
- src/base/_defaults.scss
- src/base/_typography.scss
- src/components/calendar-date/calendar-date.scss
- src/components/ground-nav/ground-nav.scss
- src/components/heading/heading.scss
- src/components/message/message.scss
- src/components/pagination/pagination.scss
- src/components/sky-nav/sky-nav.scss
- src/mixins/_headings.scss
- src/mixins/_table.scss
- src/tokens/line-height.stories.mdx
- src/tokens/number/line-height.js
- src/tokens/size/font.js
- src/tokens/size/heading.js
- src/vendor/wordpress/demo/font-size.twig
- src/vendor/wordpress/styles/_core-blocks.scss
- src/vendor/wordpress/styles/_utilities.scss
- src/vendor/wordpress/utilities.stories.mdx
- Adds and documents `has-{font-size}-font-size` utilities for the [Gutenberg block editor](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#block-font-sizes).
- Exposes more `size.font` and `number.line-height` tokens.
- Moves modular scale logic of heading calculation from Sass mixin to token definition.
- Rejoins `-n-{digit}` token names to be `-n{digit}` for consistency with class names.
- Fixes a small bug with Gutenberg quotes found along the way.
On [the deploy preview](https://deploy-preview-1333--cloudfour-patterns.netlify.app/)…
- Review Design ▸ Typography stories for regressions
- Review Components ▸ Heading stories for regressions
- Review Vendor ▸ WordPress ▸ Utilities ▸ Font Size story (try different classes using controls)
---
- See …
> Add Gutenberg font size utilities + misc. typographic token improvements

- .changeset/rare-lobsters-try.md
- src/mixins/_ms.scss
- src/vendor/wordpress/styles/_utilities.scss
- src/vendor/wordpress/utilities.stories.mdx
As part of #1333, I mistakenly thought that WordPress would preserve the structure of slugs as class names, but instead it appears to filter the slugs through a kebab-case function that treats numbers as separate words. For this reason, our Gutenberg font size utilities must output `n-2` instead of `n2` (and so on).
[Review deploy preview](https://deploy-preview-1335--cloudfour-patterns.netlify.app/docs/vendor-wordpress-utilities--font-size)
---
- See https://github.com/cloudfour/cloudfour.com-wp/issues/491
> Correct Gutenberg font size utility names

- src/components/cloud-cover/cloud-cover.stories.mdx
This PR refines the code examples for the Cloud Cover stories.
Cloud Cover stories: https://deploy-preview-1350--cloudfour-patterns.netlify.app/?path=/docs/components-cloud-cover--content
1. Review each of the story code examples for accuracy
---
- See #1289
> Refine Cloud Cover component story code examples

- .changeset/stupid-walls-sip.md
- .changeset/tender-wasps-type.md
- src/mixins/_adjacent.scss
- src/mixins/_spacing.scss
- src/objects/rhythm/rhythm.scss
- src/objects/rhythm/rhythm.stories.mdx
- src/vendor/wordpress/_wordpress.scss
- src/vendor/wordpress/jetpack-blocks.stories.mdx
- src/vendor/wordpress/styles/_jetpack-blocks.scss
See changelog and docs for details.
[On the deploy preview](https://deploy-preview-1351--cloudfour-patterns.netlify.app/):
- Review Rhythm Object docs for regressions
- Review Vendor WordPress Jetpack Markdown story
---
- Fixes #1314
> Slightly refactor Rhythm, support Jetpack Markdown Block

- .changeset/angry-wasps-sip.md
- src/components/avatar/avatar.scss
- src/components/avatar/avatar.stories.mdx
- src/tokens/size/sizing.js
See title and accompanying docs. Required for #1238.
[Deploy preview](https://deploy-preview-1358--cloudfour-patterns.netlify.app/?path=/docs/components-avatar--small-empty#small)
> Add small size of avatar

- .changeset/poor-planes-retire.md
- src/components/comment-form/comment-form.stories.mdx
- src/components/comment-form/comment-form.twig
- src/make-twig-include.js
Refine Comment Form component code examples and docs.
I also updated the template by dropping the parenthesis on the `logged_in_user` object property calls, following what I did for [PR 1300](https://github.com/cloudfour/cloudfour.com-patterns/pull/1300#discussion_r652121442).
Preview: https://deploy-preview-1353--cloudfour-patterns.netlify.app/?path=/docs/components-comment-form--default-story
1. Review code examples for accuracy
1. Review template changes
---
- See #1289
> Comment Form code example + docs + template updates

- src/components/dot-leader/dot-leader.stories.mdx
This PR refines the code example for the Dot Leader list example.
Preview: https://deploy-preview-1356--cloudfour-patterns.netlify.app/?path=/docs/components-dot-leader--list
1. Review the Dot Leader list code example for accuracy
---
- See #1289
> Refine the Dot Leader list code example

- src/components/event-log/event-log.stories.mdx
This PR refines the Event Log code example.
Preview: https://deploy-preview-1357--cloudfour-patterns.netlify.app/?path=/docs/components-event-log--example
1. Review the code example for accuracy
---
- See #1289
> Refine the Event Log code example

- src/components/heading/heading.stories.mdx
This PR refines the Heading component story code examples.
Preview: https://deploy-preview-1367--cloudfour-patterns.netlify.app/?path=/docs/components-heading--levels
1. Review the Heading component code example for accuracy
---
- See #1289
> Refine Heading component story code examples

- src/components/icon/icon.stories.mdx
This PR refines the Icon component story code examples.
Preview: https://deploy-preview-1368--cloudfour-patterns.netlify.app/?path=/docs/components-icon--basic
1. Review the Icon component story code examples for accuracy
---
- See #1289
> Refine Icon component story code examples

- .changeset/kind-beans-fry.md
- .changeset/loud-ligers-remember.md
- src/assets/icons/pencil.svg
- src/components/badge/badge.scss
- src/components/badge/badge.stories.mdx
- src/components/badge/badge.twig
- src/components/comment/comment.stories.mdx
- src/components/comment/comment.twig
- Adds a Badge component (see docs for details)
- Adds demo role badges to Comment component
- Adds `pencil` icon for "author" role badge in comments
On the deploy preview…
- [Icons](https://deploy-preview-1379--cloudfour-patterns.netlify.app/?path=/docs/design-icons--page)
- [Components ▸ Badge](https://deploy-preview-1379--cloudfour-patterns.netlify.app/?path=/docs/components-badge--basic)
- [Components ▸ Comment ▸ Role badges](https://deploy-preview-1379--cloudfour-patterns.netlify.app/?path=/docs/components-comment--role-author#role-badges)
---
- See #1238
> Add Badge component, pencil icon, demo roles to Comment

- .changeset/tricky-nails-kick.md
- src/components/heading/demo/weight.twig
- src/components/heading/heading.scss
- src/components/heading/heading.stories.mdx
- src/components/heading/heading.twig
This PR adds a font-weight modifier to change the weight to 300.
1. [Deploy link](https://deploy-preview-1394--cloudfour-patterns.netlify.app/?path=/docs/components-heading--weight)
---
- Fixes https://github.com/cloudfour/cloudfour.com-patterns/issues/1377
> Add font weight modifier

- .changeset/heavy-plums-swim.md
- src/mixins/_button.scss
This PR resolves a bug where the Button component content was not centered when the button width was larger than it's default width.
1. Confirm the Button content is horizontally centered on the **Comment Form** component ([before](https://v-next--cloudfour-patterns.netlify.app/?path=/docs/components-comment-form--default-story) / [after](https://deploy-preview-1398--cloudfour-patterns.netlify.app/?path=/docs/components-comment-form--default-story))
1. Confirm no regressions on the **Button** component ([before](https://v-next--cloudfour-patterns.netlify.app/?path=/docs/components-button--button-element) / [after](https://deploy-preview-1398--cloudfour-patterns.netlify.app/?path=/docs/components-button--button-element))
---
- Fixes #1352
> Ensure button content is centered

- src/components/icon/icon.stories.mdx
This PR removes a `console.log` that was accidentally left in the code.
> Remove console log from Icon stories

- src/objects/feature-group/feature-group.scss
- src/prototypes/article-listing/example/example.scss
- src/prototypes/article-listing/example/example.twig
Issue #1401 suggests that new heading sizes and/or a means of adjusting heading sizes is necessary. But upon viewing the prototype in question, it looked like there was very little difference between those headings and our heading component with the following settings:
```json
{
"level": -1,
"tag_name": "h2",
"weight": "light",
}
```
This PR updates that prototype to leverage the existing heading component. While there are subtle differences, they do not appear meaningful to my eye.
After making this change, running `npm run lint` also caught a CSS ordering issue that slipped by somehow. So that is also fixed to make sure this PR passes our tests.
Compare the article listing prototype headings:
- [On `v-next` (before this change)](https://v-next--cloudfour-patterns.netlify.app/iframe.html? …
> Update article listing headings, fix lint warning

- .changeset/five-turkeys-double.md
- .changeset/shaggy-pumpkins-hug.md
- src/components/button/button.scss
- src/components/heading/heading.stories.mdx
- src/components/heading/heading.twig
- src/objects/overview/demo/advanced.twig
- src/objects/overview/demo/basic.twig
- src/objects/overview/overview.scss
- src/objects/overview/overview.stories.mdx
- src/objects/overview/overview.twig
- src/prototypes/article-listing/example/example.scss
- src/prototypes/article-listing/example/example.twig
This PR adds an "Overview" object which is used on the Article Listing pages to show a full list of topics and a search bar. The Article Listings prototype was updated to use this component
1. Compare the Article Listings prototype on the [current site](https://v-next--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-article-listing--example&args=&viewMode=story) and the [preview deploy](https://deploy-preview-1406--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-article-listing--example). They should look pretty much identical
2. Confirm on the [preview deploy](https://deploy-preview-1406--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-article-listing--example)you can [use the VoiceOver rotor in Safari](https://support.apple.com/guide/voiceover/with-the-voiceove …
> Add "Overview" object for use on the Article Listing page

- src/components/button/button.stories.mdx
This PR refines the Button story code examples.
Preview: https://deploy-preview-1402--cloudfour-patterns.netlify.app/?path=/docs/components-button--button-element
1. Review the Icon component story code examples for accuracy
---
- See #1289
> Refine Button story code examples

- src/components/badge/badge.stories.mdx
This PR refines the Badge component code examples.
Preview: https://deploy-preview-1414--cloudfour-patterns.netlify.app/?path=/docs/components-badge--basic
1. Review the Badge component story code examples for accuracy
---
- See #1289
> Refine Badge component code examples

- .github/workflows/ci.yml
Closes #1421, see #1421 for reasons
[here's the docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on)
> Only run CI on PRs and pushes to v-next/main

- src/components/input/demo/example.twig
- src/components/input/demo/select.twig
- src/components/input/input.stories.mdx
This PR refines the Input component code examples and simplifies a couple of the stories as well.
Preview: https://deploy-preview-1419--cloudfour-patterns.netlify.app/?path=/docs/components-input--elastic-textarea
1. Review the Input component story code examples for accuracy
---
- See #1289
> Refine Input component code examples & simplify stories

- .github/workflows/ci.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
Closes #1294 
- I changed some of the script names to match https://github.com/cloudfour/guides/blob/main/package-json-script-names.md, and I added the `validate` script.
- I added the `start` script, which does the same thing as `npm run storybook` (per @Paul-Hebert's suggestion)
- I reordered some scripts so that Prettier runs after ESLint. This matters because if ESLint makes "fixes" to code, its fixes often do not conform to Prettier formatting. So running Prettier after ESLint makes sure that ESLint's fixes get formatted correctly.
- I documented the most-used npm scripts in contributing.md
> Rename and document npm scripts

- src/prototypes/speaking-listing/data/future.json
- src/prototypes/speaking-listing/data/speaking.json
- src/prototypes/speaking-listing/example/example.scss
- src/prototypes/speaking-listing/example/example.twig
- src/prototypes/speaking-listing/speaking.stories.js
This PR adds a prototype of the speaking page. It's an overview of talks Cloud Four has given. The design similar to the [current page](https://cloudfour.com/presents/), but uses our new patterns.
---
- This is 1/2 of issue #1417. The other part will involve prototyping the individual pages.
> Add Speaking Listing prototype

- .changeset/cold-melons-boil.md
- src/components/comment-form/comment-form.scss
- src/components/comment-form/comment-form.stories.mdx
- src/components/comment-form/comment-form.twig
- src/components/comment/comment.scss
- src/components/comment/comment.twig
- src/tokens/size/spacing.js
This PR wraps the help text in and alert, and adjust the spacing between the reply form and the comment above.
The goal is to more clearly distinguish the reply form from the comment, and make it clear that the help text is connected to the reply form, not the comment above.|
1. Review the [preview deploy](https://deploy-preview-1434--cloudfour-patterns.netlify.app/?path=/story/components-comment--with-reply-button)
---
Fixes #1427
/CC @tylersticka
> Refine the visual display of the comment reply form help text

- .changeset/short-walls-hear.md
- src/components/comment/comment.stories.mdx
- src/components/comment/comment.twig
- src/components/comment/demo/author.twig
- src/components/comment/demo/member.twig
This PR makes a change to how author/member badges can be applied to comments.
Instead of using properties for this, the template now accepts an `author_meta` slot.
This allows the consuming app to use whatever logic makes sense to determine what badge to apply.
(No visual changes)
1. Review the [preview deploy docs page](https://deploy-preview-1439--cloudfour-patterns.netlify.app/?path=/docs/components-comment--single)
---
- Fixes #1429
> Switch Comment Badging to a Slot

- .changeset/large-teachers-roll.md
- src/components/comment/comment.stories.mdx
- src/components/comment/comment.twig
The Comment template has a `replies` block allowing devs to customize how replies are output.
This block was not working correctly because it was nested inside another embed.
This PR uses `set` to define the replies outside of the embed and then pass them in.
> Fix issue with Comment `replies` block not working

- src/objects/button-group/button-group.stories.mdx
> Move button group source examples to docs code

- src/objects/deck/deck.stories.mdx
For this one I used a `transformSource` function because I thought the class names were complex enough that it would be helpful to have them match the `args` for individual stories without all the logic that's in the demo template.
---
- See #1447
> Improve deck source examples

- src/objects/embed/embed.stories.mdx
See title. As with #1452, this uses a `transformSource` function to dynamically update a source code example per story.
---
- See #1447
> Improve embed source examples

- src/objects/media/demo/calendar-date.twig
- src/objects/media/demo/checkbox.twig
- src/objects/media/media.stories.mdx
This one uses a `transformSource` function for the examples that respond to `args` and `raw-loader` for the examples that are static. The static examples were updated slightly to improve the copy-ability of the source code.
---
- See #1447
> Improve media source examples

- src/base/_themes.scss
- src/components/ground-nav/ground-nav.scss
- src/components/ground-nav/ground-nav.twig
- src/design/demo/theme-alternate.twig
- src/design/themes.stories.mdx
- src/prototypes/case-study-listings/example/example.scss
- src/prototypes/case-study-listings/example/example.twig
This PR introduces an "alternate" theme. Closes #1380. 
Preview: https://deploy-preview-1458--cloudfour-patterns.netlify.app/?path=/docs/design-themes--alternate-with-light
> Introduces an "alternate" theme

- .changeset/dirty-seals-cheat.md
- src/base/_fonts.scss
This is a performance improvement, part of https://github.com/cloudfour/cloudfour.com-wp/issues/511.
`font-display: swap` makes the browser display fallback fonts immediately, until the requested font is loaded. Without this property, the browser displays no text for a short delay, and only displays the fallback font after a timeout, and if the requested font has still not loaded after the timeout.
I tested it on cloudfour.com locally by editing the font declarations in the node_modules folder. By repeatedly doing a hard-refresh with caching disabled, I could see that with `font-display: swap` the fallback font gets displayed right away.
> Use font-display: swap in font declarations

- .changeset/fluffy-ads-brush.md
- src/components/heading/demo/weights.twig
- src/components/heading/heading.scss
- src/components/heading/heading.stories.mdx
I found a case where I wanted to **bold** some words inside of `c-heading--light`, but the `font-weight` only increased one level. This adds overt `b` and `strong` styles to that modifier to make this possible. It also updates the demo to showcase this feature.
> Support b and strong from c-heading--light

- .changeset/good-ducks-share.md
- .changeset/lazy-bees-perform.md
- src/mixins/_spacing.scss
- src/objects/rhythm/demo/article.twig
- src/objects/rhythm/rhythm.scss
- src/objects/rhythm/rhythm.stories.mdx
While providing feedback for @AriannaChau's article prototype, I became aware of two issues with `o-rhythm`:
- There was no way to revert to the default rhythm in nested rhythm embeds. So in this PR, I've added the `o-rhythm--default` modifier for this purpose.
- The `--generous-headings` modifier was ineffective on `c-heading` elements. In this PR, I've added a `[class*='heading']` selector to the vertical spacing mixin to serve this purpose in an extensible way.
These screenshots both show an `o-rhythm--generous-headings` element with a plain `h2` and a `c-heading` of the same level. The spacing before each should be equal.
> Two o-rhythm improvements

- .changeset/mean-spies-glow.md
- src/components/comment-form/comment-form.stories.mdx
- src/components/comment-form/comment-form.twig
- src/components/comment/comment.stories.mdx
- src/components/comment/comment.twig
This makes some changes to our components to allow the Wordpress site to properly set up comment form submission.
I'm like 90% sure this will be all we need. There's a chance we'll need to do a follow-up PR if things don't work as expected in WP land.
The comment form got a new `hidden_inputs` block which allows you to pass in `<input type="hidden">` elements, which Wordpress requires for comment submission. (We technically could have done this already with the `prompt` block, but that felt kinda gross and I had to make other changes.)
This component required more changes so that it can configure its nested Comment Form:
- `reply_form_action`: the action for the reply form
- `reply_form_method`: the method for the reply form
- `reply_form_hidden_inputs`: This allows you to pass in content …
> Add options to Comments and Comment Forms to allow submission

- .changeset/few-ducks-shake.md
- src/components/comment-form/comment-form.twig
While testing https://github.com/cloudfour/cloudfour.com-wp/pull/592 Tyler noticed that the email input was missing a name attribute and breaking comment submission. This fixes that.
> Add missing `name` attribute to Comment Form email input

- package-lock.json
- src/prototypes/single-article/single-article.stories.js
- src/prototypes/single-page/single-page.stories.js
- src/prototypes/team/team.stories.js
- src/prototypes/use-sky-nav.ts
Closes https://github.com/cloudfour/cloudfour.com-patterns/issues/1473
I made a custom hook `useSkyNav` that initializes the sky nav. In prototypes that have the sky nav, the hook needs to be called:
```js
export const SomePrototypeStory = () => {
useSkyNav()
return someTwigFile()
}
```
Make sure that all the prototypes that use the sky nav initialize the JS correctly for small screens
> Initialize sky nav JS for all prototypes that use the sky nav

- .changeset/ten-parrots-battle.md
- src/components/sky-nav/sky-nav.scss
https://github.com/cloudfour/cloudfour.com-patterns/issues/1514
https://deploy-preview-1517--cloudfour-patterns.netlify.app/iframe.html?id=components-sky-nav--dark&viewMode=story&args=&globals=
> Scale down logo more for small screens

- .changeset/famous-peaches-punch.md
- src/components/button/button.stories.mdx
- src/components/button/button.twig
- src/components/button/demo/icon-button-custom-demo.twig
- src/components/button/demo/slashed-icon-button-custom-demo.twig
- src/mixins/_button.scss
This PR refactors the Button component in response to #1508. Changes include:
- remove the `aria-pressed` logic
- introduce a `is-slashed` CSS state class
1. Review https://deploy-preview-1519--cloudfour-patterns.netlify.app/?path=/docs/components-button--slashed-icon#icon-with-slash
---
- Closes #1509
> Introduce Button 'is-slashed' CSS state class, remove aria-pressed logic

- .changeset/rude-pears-breathe.md
- src/components/comment/comment.twig
Recently @gerardo-rodriguez pointed out:
> While testing a PR with VoiceOver, I noticed that the rotor lists all comments as "article". It seems we might be able to enhance the experience by adding accessible names to the <article> elements? (e.g. aria-labelledby)
This PR adds `aria-labelledby` to link the existing comment headings to the comment article.
You're gonna wanna hide whitespace changes while reviewing. There was an indentation issue in the file that was fixed as well.
1. Review  `/?path=/story/components-comment--with-reply-thread` on the preview deploy in VoiceOver. Check the rotor and note the articles have accessible names.
> Use aria-labelledby to add accessible names to articles

- .changeset/pretty-ducks-wave.md
- src/components/ground-nav/ground-nav.scss
This PR makes a small change of increasing whitespace in the ground nav component so it doesn't look so squished against different backgrounds.
Before:
After:
1. [Deploy link](https://deploy-preview-1533--cloudfour-patterns.netlify.app/?path=/story/components-ground-nav--cloud-four)
---
- Fixes https://github.com/cloudfour/cloudfour.com-patterns/issues/1528
> Incease whitespace for the ground nav component

- .github/workflows/ci.yml
- package.json
Our tests rely on importing files from `/dist` to work correctly. However, for `dist` to be present, you need to run `build` first. So if you run `validate` before building you can end up with unexpected errors like this:
Since it's possible to make changes to the patterns without ever running `build` there's a good chance you're validating against an outdated `dist` directory when running `validate` This PR updates our `validate` script to build the project before testing.
As I was writing this it occurred to me that the `test` script should maybe run `build` instead? But it feels like that might be unexpected, whereas I expect `validate` to go off and do a bunch of different things.
If we did move this to the `test` script, then what does that mean for `test:watch`. Does it also need to …
> Build the project before validating

- .github/workflows/changesets.yml
In a [dep update PR](https://github.com/cloudfour/cloudfour.com-patterns/pull/1538) I changed the npm version being used to v7, because github was failing to install the packages using npm 6: https://github.com/cloudfour/cloudfour.com-patterns/compare/43e5a38...e640e35
But, I forgot to also update the changeset release workflow to also use npm 7, so now it fails. This PR updates the npm version in that as well.
> Fix npm version used in release workflow

- .changeset/light-avocados-enjoy.md
- src/base/_defaults.scss
- src/components/alert/alert.scss
- src/components/alert/alert.stories.mdx
- src/components/alert/alert.twig
- src/components/card/card.scss
- src/mixins/_border-radius.scss
- src/objects/container/container.scss
- src/vendor/wordpress/styles/_core-blocks.scss
- src/vendor/wordpress/styles/_utilities.scss
This PR adds a mixin for [Ahmad Shadeed's conditional border radius technique](https://ishadeed.com/article/conditional-border-radius/), and applies that technique to various elements:
- Code blocks now have rounded corners above full-width by default. This will appear more consistent with other block elements like groups and cards.
- Alerts no longer require a `full-width` modifier. (I don't consider this a breaking change because the existing options have no effect.)
- Contained cards no longer require border radii negation. This removes the need to include complicated `border-radius` rules in the otherwise layout-focused container object.
- Gutenberg styles for pull quotes, backgrounds and groups have been significantly streamlined.
---
- Fixes #1559
> Conditional rounded corners

- .changeset/fifty-pigs-sniff.md
- src/base/_defaults.scss
- src/design/defaults.stories.mdx
- src/vendor/wordpress/core-blocks.stories.mdx
- src/vendor/wordpress/styles/_core-blocks.scss
We lacked a default style for `hr`. This changes that. It uses the top border of `footnote-group` for basic appearance, but takes more color cues from the left comment border so that it will have slightly better contrast (and better compatibility with secondary themes). (I resisted the urge to style the footnote group to match because that feels like a visual distinction that does not necessarily warrant greater contrast.)
It also extends those styles to the WordPress "Separator" block.
---
- Fixes #1520
> Style horizontal rules and separators

- .changeset/ninety-hotels-jump.md
- src/base/_typography.scss
- src/components/card/card.scss
- src/components/sky-nav/sky-nav.scss
- src/mixins/_fluid.scss
- src/mixins/_headings.scss
- src/objects/bio/bio.scss
- src/objects/container/container.scss
- src/objects/deck/deck.scss
- src/objects/feature-group/feature-group.scss
- src/objects/list/list.scss
- src/objects/overview/overview.scss
- src/prototypes/article-listing/example/example.scss
Replaces our property-specific "fluid" mixins with a more versatile `fluid-clamp` function based on an example by @Paul-Hebert. The output is greatly simplified by replacing media queries with [the `clamp` function](https://caniuse.com/css-math-functions).
I marked this as a breaking change since it slightly reduces browser support, it removes mixins that were previous available, and it changes the argument order of the remaining functions (what we had previously wasn't very intuitive). But I'm open to feedback if that feels too aggressive.
Compare various components, objects and prototypes on the deploy preview and compare to the `v-next` version for regressions.
---
- Fixes #1560
> Simplify fluid values using clamp

- .changeset/thirty-foxes-melt.md
- src/components/card/card.stories.mdx
- src/components/card/card.twig
@Paul-Hebert made a good suggestion to add support for the `aria-labelledby` property on articles to improve the experience of navigating between them via the VoiceOver rotor. After some research in [the web-a11y Slack](https://www.tpgi.com/anybody-can-be-an-a11y-slacker/), I couldn't see any downside to adding this as an option.
I originally implemented the `heading_id` and a separate `aria_labelledby` property, but this felt a bit silly since they should always be the same. Instead, I simplified it down to a single `heading_id` option. If the `heading_id` is specified and the `heading` block isn't empty, it's automatically output to `aria-labelledby` on the root element as well. I wasn't sure if the label had to be on the _heading_ or the immediate container of the heading text (in …
> Add heading_id option to card template

- .changeset/new-pets-care.md
- .changeset/odd-sloths-allow.md
- .changeset/tough-books-sing.md
- src/components/button/button.scss
- src/components/icon/icon.scss
- src/components/icon/icon.stories.mdx
- src/design/icons/icons.stories.mdx
- src/mixins/_button.scss
- src/prototypes/article-listing/example/example.scss
- src/prototypes/article-listing/example/example.twig
Addresses an issue where icons were inconsistently sized if included as the primary button content, as one might expect for an icon-only button.
Previously, button icon sizes were controlled via `font-size` on the icon container, `c-button__extra`. When an icon was included as the primary content, `c-button__content`, there was no such `font-size` declaration, and so the icon would appear smaller by comparison.
I considered adding some utility classes and/or icon modifiers to solve this problem, but I realized when futzing with the component that there were other potential issues with relying on `font-size` on a containing element. For example, it's impossible to reliably negate the gap between the `__extra` and `__content` elements since the `font-size` for the icon increases the …
> Add `--icon-size` property, use within `c-button`

- src/design/demo/theme-alternate.twig
- src/design/demo/theme-content.twig
- src/design/demo/theme.twig
- src/prototypes/single-article/example/example.twig
This PR fixes a bug where the theme pages were trying to include a
twig template that was deleted in #1569. This restores that template
in a new name to make it clear it's used in the theme pages.
Review the [Theme pages](https://deploy-preview-1587--cloudfour-patterns.netlify.app/?path=/story/design-themes--light) and [Single Article prototype](https://deploy-preview-1587--cloudfour-patterns.netlify.app/?path=/story/prototypes-single-article--example) on the preview deploy. They should not display an error.
---
- Fixes #1585
> Fix Theme Pages

- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- package.json
- src/components/alert/alert.stories.mdx
- src/components/cloud-cover/cloud-cover.stories.mdx
- src/components/ground-nav/ground-nav.stories.mdx
- src/components/sky-nav/sky-nav.stories.mdx
- src/design/favicons.stories.mdx
- src/objects/container/container.stories.mdx
- src/objects/page/page.stories.mdx
- src/prototypes/article-listing/articles.stories.js
- src/prototypes/articles/articles.stories.js
- src/prototypes/card-variations/card-variations.stories.js
- src/prototypes/case-study-listings/case-study-listings.stories.js
- src/prototypes/cloud-divider/clouds.stories.js
- src/prototypes/comment-thread/thread.stories.js
- src/prototypes/email-signup/signup.stories.js
- src/prototypes/error/error.stories.js
- src/prototypes/home-page/home-page.stories.js
- src/prototypes/no-content/no-content.stories.js
- src/prototypes/no-results/articles.stories.js
- src/prototypes/quotes/quotes.stories.js
- src/prototypes/single-article/single-article.stories.js
- src/prototypes/single-page/single-page.stories.js
- src/prototypes/speaking-event/speaking.stories.js
- src/prototypes/speaking-listing/speaking.stories.js
- src/prototypes/team/team.stories.js
[A bug popped up a while ago in the Storybook padding add-on we used](https://github.com/rbardini/storybook-addon-paddings/issues/28), but it's been a challenging issue for the developer to resolve because of some very odd markup structure in Storybook Docs.
Although our add-on supported multiple steps in our modular scale, I realized when looking at the various stories that we were only ever applying or disabling the add-on. This makes the value of the toolbar item questionable compared to the `layout` feature that Storybook includes, which can be set to `fullscreen` for stories that are meant to fill the viewport width.
So this PR removes the add-on, and replaces any parameters related to removing padding with `layout: 'fullscreen'`.
---
- Fixes #1371
> Remove paddings add-on

- src/objects/page/page.scss
- src/prototypes/single-article/example/example.twig
This PR fixes a bug where blog posts that contained lengthy code samples were breaking layout. The bug wasn't actually caused by the code samples, which have the proper `overflow:auto` property set. Instead, this is caused by an oddity of Grid layouts, where the Grid items by default have `min-width:auto`, which can prevent them from reducing width the way you might expect. The fix is to tell the Grid layout the minimum width for Grid items, and then it will shrink the way you'd expect.
Learn more: https://css-tricks.com/you-want-minmax10px-1fr-not-1fr/
Unfortunately, the bug was not visible in the pattern library, because we weren't applying the Page object to the Single Article prototype. This PR applies that change so we can test the fix.
1. visit the [Single Article …
> Add min-width to Page contents

- .changeset/modern-turtles-hear.md
- src/components/card/card.scss
This is a [depressingly old](https://bugs.webkit.org/show_bug.cgi?id=68196) bug. [This solution](https://stackoverflow.com/a/16681137) seemed to function the best, but I simplified it because the pattern does not use 3D transforms and those properties no longer require vendor prefixes.
Review linked cards with covers. Confirm that they no longer break overflow or border radius on hover in Safari.
---
- Fixes #1597
> Fix Card cover hover issue in Safari

- .changeset/ten-candles-guess.md
- src/objects/list/list.scss
- src/objects/overview/demo/advanced.twig
- src/prototypes/article-listing/example/example.twig
This PR fixes three Safari issues that were visible in different situations in the article topics listing:
- Any `u-hidden-visually` elements within the list would cause Safari to increase the scrollable height of the window. This was resolved by adding `position: relative` to children of the list. (It was not effective to add this to the parent.)
- Some elements would appear divided between columns. This was resolved by adding `break-inside: avoid` to children of the list. (`page-break-inside` and `-webkit-column-break-inside` are common suggestions, but these are older properties that didn't seem to have any more effect)
- The bottom margin of an item could carry into the next column. This was fixed by swapping `u-space-block-end-0` with `u-pad-block-end-0` in the relevant templates. …
> Fix issues related to columned lists in Safari

- README.md
Quick edit I noticed while browsing the repo
Link was to netlify.com instead of netlify.app
Visual changes should include a screenshot.
1. Click on the link to the Netlify preview.
2. See it works
---
- Fixes # (issue)
/CC @tylersticka
> Fix: Broken Netlify link

- .changeset/gentle-grapes-camp.md
- src/components/avatar/avatar.stories.mdx
- src/components/avatar/avatar.twig
Adds `width` and `height` properties to the Avatar component's Twig template. This has no impact on the visual appearance of the element (since it is using an aspect ratio hack for layout) and no performance impact (since modern browsers will use `sizes` to determine the best `srcset` image), but it does provide a means of constraining the size in case the CSS fails to load or the page is viewed using an alternative user agent or older browser.
Because Avatars are circular, you can provide either `width` or `height` and it will be used as the default for the other.
These tests involve [viewing an Avatar story's "canvas" tab](https://deploy-preview-1713--cloudfour-patterns.netlify.app/?path=/story/components-avatar--with-image), changing its properties and observing the "HTML" tab to …
> Add width/height properties to Avatar component

- src/components/card/card.stories.mdx
- src/components/heading/heading.stories.mdx
- src/objects/deck/deck.stories.mdx
- src/objects/embed/embed.stories.mdx
This PR updates certain story files to no longer assume that the `storyContext` argument will contain an `args` object. This makes those pages visible again.
Confirm in the deploy preview the visibility of affected pages:
---
- Fixes #1692
> Don't assume storyContext.args exists

- .changeset/thirty-beans-act.md
- src/components/author/author.stories.mdx
- src/components/author/author.test.ts
- src/components/author/author.twig
The [Talks + Events listing page](https://v-next--cloudfour-patterns.netlify.app/?path=/story/prototypes-speaking-listing--example) calls for the Author component to allow author names to be not linked. This PR sets up the author `link` prop to be optional.
1. Review the [Author component page](https://deploy-preview-1718--cloudfour-patterns.netlify.app/?path=/docs/components-author--with-no-link) and confirm a `<span>` is rendered instead of an `<a>` for the default "no link" demo for the author name.
---
- Closes #1715
> Make the author link prop optional

- .changeset/beige-books-battle.md
- src/components/author/author.stories.mdx
- src/components/author/author.twig
This PR modifies the Author component to allow the `avatar` property of an `authors` array item to be an object. If an object containing at least a `src`, it will be passed directly to the Avatar component. Otherwise, it will be passed as the Avatar `src` as it was before.
This will allow developers the option of preparing a more detailed `avatar` object including whatever properties Avatar supports, for example `srcset` and `sizes`.
**Note:** I also considered creating a `block` for avatars, but since the author information is provided as an array, it seemed weird to have the avatars customizable only as a block and not as data. But I'm open to feedback on that!
1. [View the multiple authors story in Canvas view](https://deploy-preview-1719--cloudfour-patterns.netlify.app/?path=/story/com …
> Author avatar prop can be an object

- .storybook/main.js
- package.json
[Storybook 6.4 replaced the `-s` CLI flag with a `staticDirs` configuration property](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag). This applies that change to resolve a deprecation warning.
1. Confirm that there were no build errors on this PR
1. On the deploy preview, confirm that [the Logo Group story](https://deploy-preview-1722--cloudfour-patterns.netlify.app/?path=/story/objects-logo-group--default-story) still displays correctly (the client logos are all static)
> Move static directories to configuration

- .changeset/shy-fireants-mix.md
- src/components/event-log/demo/events.json
- src/components/event-log/event-log.stories.mdx
- src/components/event-log/item.twig
This adds support for a `heading_id` property for individual Event Log items. When provided, it will be used as the `id` of the heading and within the `aria-labelledby` property on the containing article, which can [improve the screen reader experience](https://support.apple.com/guide/voiceover-guide/navigate-using-the-rotor-mchlp2719/web). This also makes it consistent with our Card component.
1. [View the Event Log story](https://deploy-preview-1720--cloudfour-patterns.netlify.app/?path=/story/components-event-log--example)
2. Confirm that the markup contains example `id` and `aria-labelledby` attributes
3. Confirm that the experience is improved using Safari VoiceOver.
---
- Fixes #1707
> Add heading_id property to Event Log

- .changeset/good-ligers-arrive.md
- src/components/author/author.stories.mdx
- src/components/author/author.twig
My #1719 feature addition was buggy: The check for `author.avatar.src` only works in very specific situations. This removes that check to avoid regressions.
In its place, it adds support for template blocks to this. This allows the content of the avatars to be manipulated directly. For example:
```twig
{% embed '@cloudfour/components/author.twig' with { authors: authors, date: date } only %}
{% block avatars %}
{% for author in authors %}
{% include '@cloudfour/components/avatar/avatar.twig' with {
src: 'anything you want',
srcset: 'you got it',
sizes: 'anything you need',
width: 'you got it'
} only %}
{% endfor %}
{% endblock %}
{% endembed %}
```
Just to be safe, it's probably best that someone goes into our WordPress theme, pulls these changes into the `node_modules` locally, confirms …
> Replace buggy Author avatar object with block

- .changeset/eighty-berries-knock.md
- src/components/author/author.stories.mdx
- src/components/author/author.test.ts
- src/components/author/author.twig
This PR adds two new features to the Author component. First, it adds
the `unlink` property, which will prevent a link from being rendered
even if one is provided as part of the Author object. This is useful
for situations where removing the link property from the Author is
a hassle. Second, it adds a `date_format` property, which can be set
to `short` to use abbreviate date formatting.
1. On the preview deploy, ensure that the `short` date format displays correctly
1. ensure the `unlink` property removes the author link when provided.
2. ensure tests pass on this PR
> Add Short Date Format and Unlinking to Author

- .changeset/purple-drinks-tell.md
- src/base/_typography.scss
- src/prototypes/article-listing/data/recent.json
- src/prototypes/case-study-listings/example/example.twig
- src/prototypes/comment-thread/example/example.twig
- src/prototypes/single-article/example/example.twig
- src/prototypes/single-page/example/example.twig
- src/prototypes/speaking-event/example/single-speaker.twig
- src/prototypes/team/example/team-articles-page2.twig
- src/prototypes/team/example/team-individual.twig
This PR changes our typography stylesheet from using the `break-word`
value of `overflow-wrap` to `anywhere`, which allows the line breaks
added to be considered when calculating min-content intrinsic sizes,
such as in CSS Grid layouts. Previously, long words were failing to
break in CSS Grid contexts like Card layouts.
It also updates many of our Prototypes to include a long string,
so we can test that it's working properly in more contexts.
On the preview deploy, review the following prototypes:
In the following browsers:
Note that support for this CSS was added in Safari 15.4, so if you test in an older version, it may not work.
---
- Fixes #1729
> Use `overflow-wrap:anywhere` for Word Breaking

- .storybook/preview.js
Fixes #1695 
You can test patterns that have auto-generated source code previews, for example:
- https://deploy-preview-1733--cloudfour-patterns.netlify.app/?path=/docs/components-alert--basic
- https://deploy-preview-1733--cloudfour-patterns.netlify.app/?path=/docs/components-author--basic-usage
Tyler did most of the figuring out/fixing, and I just added a fallback for `storyContext.initialArgs`.
I did not fix the syntax highlighting, I don't remember how that works and I don't know how to fix it
> Fix automatic source code previews

- .storybook/preview.js
This is a follow-up to #1733 and restores Twig syntax highlighting to code samples. In a previous version of Storybook docs, the language of the source samples was detected automatically, but at some point this seems to have changed to use the base framework (which honestly makes some sense and is probably more performant). This simply sets the default value of the `docs.source.language` parameter to `'twig'`, which resolves the issue. This can still be overridden manually for specific stories or for code blocks with a language defined.
1. View deploy preview
2. Confirm that Twig code previews are correctly highlighted
---
- See #1695
> Fix Twig syntax highlighting

- src/components/card/card.stories.mdx
I assumed that the performance issues on the Card docs page were related to the failing syntax highlighting, but that was a poor assumption since that page is defining its own `transformSource` function. It turns out that the unique ID fallback for `heading_id` was triggering a reevaluation in Storybook, which would then generate a new unique ID, which resulted in an endless loop.
This PR replaces the fallback ID with one using the story's ID, which won't be invalidated. This makes the page usable again.
Try viewing the docs tab for the Card component, confirm it no longer causes the browser tab to hang.
> Fix Card docs performance issue

- .changeset/tasty-rules-argue.md
- src/objects/container/container.scss
- src/prototypes/home-page/example/example.twig
- src/prototypes/single-article/example/example.twig
- src/tokens/size/padding.js
In a PR discussion, @gerardo-rodriguez and I observed that every single page was overriding the container's block padding. The padding values for container are the same in both dimensions, but that simply didn't look balanced when the container was adjacent to something like the Cloud Cover with its viewport units.
This PR uses the same values as the Deck gap. But to do that, I had to break apart the vertical and horizontal padding tokens, which is why I consider this a breaking change (since references to the old token would now result in an error). Happy to modify that if others feel it's a bit too extreme.
1. On the deploy preview, observe that [the block padding in the container stories](https://deploy-preview-1740--cloudfour-patterns.netlify.app/?path=/story/objects-container--basic) …
> Increase container block/vertical padding

- .changeset/silent-carpets-doubt.md
- src/components/author/author.twig
A recent change to the Author component unintentionally added spaces
between the author names and trailing commas when there are multiple
authors. This PR removes the whitespace to prevent this.
On the preview deploy, review the [Multiple Author story](https://deploy-preview-1742--cloudfour-patterns.netlify.app/?path=/story/components-author--multiple-authors), and confirm there are no spaces between the name and the comma (contrast with the [live version](https://v-next--cloudfour-patterns.netlify.app/?path=/story/components-author--multiple-authors)).
> Remove Stray Spaces from Author Component

- .changeset/heavy-kings-arrive.md
- src/base/_defaults.scss
- src/objects/container/container.scss
- src/objects/deck/deck.scss
- src/objects/deck/deck.stories.mdx
- src/objects/deck/demo/alignment.twig
- src/objects/deck/demo/articles.twig
This PR updates the Deck object to better handle the WordPress block
alignment styles `alignwide` and `alignfull`. By default, these would
pull the Deck content flush with the edge of the screen and even clip
a bit in certain circumstances. To resolve this, we add some padding
to prevent the content from going full-bleed.
1. Check out this branch locally
1. Review the "[Block Alignment](http://localhost:6006/?path=/story/objects-deck--block-alignment)" story in the Deck page. Try changing the alignment to test both "Wide" and "Full" at several breakpoints.
- The content should not touch the edge of the viewport
- The content should not get cut off
- There should be no horizontal scrollbar
Test the following browsers:
---
- Fixes #1743
> Updated Block Alignment Styles for Deck

- .changeset/stupid-moose-march.md
- src/components/event-summary/event-summary.stories.mdx
Not critical, but something I noticed along the way.
> Add missing EventSummary `note` prop documentation

- .changeset/nasty-bags-jog.md
- src/components/subscribe/subscribe.stories.mdx
- src/components/subscribe/subscribe.test.ts
- src/components/subscribe/subscribe.twig
This PR adds the ability to pass a value for the `name` attribute to the subscription form email input. 
This is a blocker for https://github.com/cloudfour/cloudfour.com-wp/issues/560
Open the [Subscribe component](https://deploy-preview-1765--cloudfour-patterns.netlify.app/?path=/story/components-subscribe--default-story) and confirm:
---
- Closes #1766
> Allow input `name` attribute value to be set for Subscribe component

- .changeset/eight-roses-breathe.md
- src/utilities/text/demo/text-align.twig
- src/utilities/text/text.scss
- src/utilities/text/text.stories.mdx
This PR adds a `u-text-center` utility CSS class.
This was introduced to help with the ["More clients we've worked with" heading](https://deploy-preview-1742--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-case-study-listings--example&viewMode=story) (this is a blocker for https://github.com/cloudfour/cloudfour.com-wp/pull/682)
1. Review https://deploy-preview-1771--cloudfour-patterns.netlify.app/?path=/docs/utilities-text--text-align-center
---
- Closes #1772
> Add u-text-center utility

- .changeset/flat-bobcats-lie.md
- .prettierignore
- src/mixins/_spacing.scss
- src/objects/container/container.scss
- src/objects/deck/deck.scss
- src/vendor/wordpress/core-blocks.stories.mdx
- src/vendor/wordpress/demo/code.twig
- src/vendor/wordpress/styles/_core-blocks.scss
This PR updates the styles for Gutenberg Code blocks and fenced code
sections in Markdown blocks to outdent the block so the code is aligned
with the page content.
1. Review the Code block section of the WordPress Core Blocks page.
> Outdent Code Blocks

- .changeset/tricky-dots-vanish.md
- src/vendor/wordpress/demo/code.twig
- src/vendor/wordpress/styles/_core-blocks.scss
This PR updates the styles for Code blocks to not wrap, since we prefer
to use overflow to scroll.
Review the Code block on the WordPress Core Blocks page and ensure that the code does not wrap.
> Do Not Wrap Code Blocks

- .changeset/green-fishes-hug.md
- src/objects/media/media.scss
- src/objects/media/media.stories.mdx
- src/objects/media/media.twig
This PR proposes adding an `o-media--align-start` modifier. See #1792 for an example use case.
1. Review https://deploy-preview-1791--cloudfour-patterns.netlify.app/?path=/docs/objects-media--align-start#align-start
---
- Closes #1792
> Add Media object Align Start modifier

- .changeset/forty-bottles-move.md
- src/base/_defaults.scss
- src/objects/page/page.scss
Closes #1754
- Fixes the double-scrollbar issue
- Preserves the "pin to bottom" behavior of the footer for short pages
In order to reproduce this issue you must set the visible scrollbars macos option:
- Get your local wp running
- Link your `@cloudfour/patterns` in the wp site to your local copy:
- Go to your local repo copy of `@cloudfour/patterns`
- `git checkout fix-double-scrollbar`
- `npm run build`
- `npm link` - this sets up a global symlink to this copy of the repo
- Go to your local wp folder
- `cd app/public/wp-content/themes/cloudfour2021`
- `npm link @cloudfour/patterns` - this sets up that folder in node_modules to be symlinked to your local copy of the repo.
- Hard-refresh pages in the browser to make sure the new CSS is read through the symlinks
- Test a short page (that …
> Fix double scrollbar issue

- .changeset/cyan-pots-divide.md
- src/objects/deck/deck.stories.mdx
- src/objects/deck/deck.twig
Closes #1770. I will send a follow-up PR to cloudfour.com-wp.
[Deploy preview](https://deploy-preview-1804--cloudfour-patterns.netlify.app/?path=/story/objects-deck--basic), check that changing the `tag_name` prop actually changes the tag name.
> Allow customizing `tag_name` for deck object

- .changeset/perfect-rats-raise.md
- src/vendor/wordpress/core-element-comparison.stories.mdx
- src/vendor/wordpress/demo/compare-gutenberg.twig
- src/vendor/wordpress/demo/compare-html.twig
- src/vendor/wordpress/demo/compare-markdown.twig
- src/vendor/wordpress/styles/_core-blocks.scss
This PR adds a new "Core Element Comparison" set of stories to the
WordPress section. These stories compare how we style core HTML
elements added via Markdown blocks, HTML blocks, and Gutenberg blocks.
We want them to have the same (or very comparable) styles.
Next steps: I will create a followup PR for the WordPress theme to tweak a few editor styles (notably, the Blockquote block has no styles applied to it, and is indistinguishable from plain text).
On the preview deploy, visit the new "WordPress > Core Element Comparison" page, and verify that the styles for all the elements show matches.
Known issue: The image block is center aligned by default, while standard images are not. This is fine, since most images in our blocks use alignment utility classes as needed.
---
- Fixes #1522
> Add Core Element Comparison Stories

- .changeset/rich-jobs-fold.md
- src/components/ground-nav/ground-nav.scss
Switches from using `font-size` to `--icon-size` to define the social icon size. This fixes an issue where the `font-size` was not respected because Ground Nav's CSS include is alphabetically before the Icon component's.
Alternatively I could have moved the sizing to another element, but I think I may create a second issue for cleaning up this component's structure a bit in general (there seem to be some unused classes and such as well).
I also replaced the use of a mixin to generate the size with a design token (which did not exist at the time).
---
- Fixes #1821
> Use custom property for social icon size

- src/components/cloud-cover/cloud-cover.stories.mdx
- src/components/cloud-cover/cloud-cover.twig
- src/components/cloud-cover/demo/content.twig
- src/components/cloud-cover/demo/extra.twig
- src/components/cloud-cover/demo/scene.twig
Here's the changes we were trying to make:
- Cloud Cover now has both a `content` and a `heading` block
- ~Moved the rhythm block to the component, and used HTML rather than an embed because the nested blocks were causing problems (maybe @tylersticka knows how to fix that?)~
- Updated the source code in the MDX file
You'll want to [hide whitespace changes](https://github.com/cloudfour/cloudfour.com-patterns/pull/1834/files?diff=unified&w=1) when reviewing this…
> Update Markup Structure for Cloud Cover

- .changeset/early-cups-clean.md
- src/vendor/wordpress/core-blocks.stories.mdx
- src/vendor/wordpress/styles/_core-blocks.scss
This PR updates the default styling for Gutenberg Column blocks to add
our standard rhythm styles to the columns, so their contents will be
properly spaced.
1. Review the "Vendor > WordPress > Core Blocks > Columns" story on the preview deploy.
1. Confirm the heading and paragraphs have spacing between them.
---
- Fixes #1827
> Give Columns Rhythm

- .changeset/fifty-terms-beg.md
- src/components/cloud-cover/cloud-cover.scss
- src/components/sky-nav/sky-nav.scss
- src/components/sky-nav/sky-nav.twig
- src/prototypes/speaking-listing/example/example.twig
- src/tokens/size/padding.js
- src/tokens/size/shirts.json
- src/tokens/size/sizing.js
Makes a handful of sizing and spacing tweaks based on actual site content. Specifically:
- Lowered the "shirt size" widths starting with `xl`. Previously, content was widening to a size that made it difficult to compose imagery without it filling most of the viewport.
- Increased the Sky Nav max width and adjusted the Sky Nav logo padding so that it won't appear indented too far right.
- Reduced the size of the "cloud space" for the Cloud Cover component so these items won't be _quite_ so tall.
- Increased the minimum size of Deck object columns. In combination with the shirt size change, this means Deck objects will naturally limit themselves to three columns, which may eliminate the need for classes within our templates.
- Increased the amount of horizontal fluid padding (both minimum …
> Misc. layout adjustments

- .changeset/cuddly-hairs-compare.md
- src/components/card/card.scss
- src/tokens/number/brightness.json
A lot of our feature images include a light silver background. This is an issue in `t-alternate` containers where that is the background.
This PR implements a suggestion from @Paul-Hebert to use a brightness filter to subtly offset imagery within these containers.
The "pros" of this approach are that it does not require changes to actual assets or any specific action on the part of the developer or content author. The potential con is that it does result in a slight color shift for some images, but I think the shift is subtle enough to be acceptable for secondary content containers (which `t-alternate` is, by nature, intended for).
Note how the left and right edges blend in a _little_ less with the background than before:
Before | After
--- | ---
1. [Open up the deck …
> Brighten card covers in alternate theme

- .changeset/thin-worms-whisper.md
- src/components/card/card.scss
- src/components/event-summary/event-summary.scss
Previously, Button components had distinct hover and active states. But other interactive components with scale effects did not have `:active` states.
This PR adds the same Button `:active` effects to Event Summary calendars. Because card covers are a bit larger and would be jarring, the `:hover` state is simply negated on `:active`. This should make these interactive elements feel a bit more consistent across the site.
Here is how the Button looks already for `:hover`, then `:active`:
And here's how the Event Summary and Card components look in this PR:
Test `:hover` and `:active` states in:
1. [Event summary](https://deploy-preview-1852--cloudfour-patterns.netlify.app/?path=/story/components-event-summary--default-story)
2. [Card with …
> Add active styles for Card and Event Summary

- .changeset/rare-trainers-heal.md
- src/base/_defaults.scss
- src/base/_themes.scss
- src/utilities/border/border.scss
- src/utilities/border/border.stories.mdx
This PR adds some border utilities to help us offset images from their background in articles.
These function [similarly to the last version](https://cloudfour-patterns.netlify.app/patterns/utilities.html#border), with a few key differences:
- There's now a default (`u-border`).
- The sizes are now fully spelled out, consistent with modifiers like `avatar--small`.
- The default color is based on the current theme.
- The utilities only output `border-width` with `!important`: The default color and style are now applied using `:where`, which eliminates the need for the separate "just the width" classes we had before.
- No directional variations (top, right, bottom, left) or responsive classes. This time around, these are mainly intended for use within content, so these aren't as critical as …
> Add border utilities

- .changeset/perfect-seahorses-knock.md
- src/utilities/size/demo/inline-size.twig
- src/utilities/size/demo/responsive.twig
- src/utilities/size/demo/styles.scss
- src/utilities/size/size.scss
- src/utilities/size/size.stories.mdx
Adds a set of responsive `u-size-inline-*` utilities to allow for percentage-based sizing of one-off content elements.
Similar to [the previous version](https://cloudfour-patterns.netlify.app/patterns/utilities.html#size) except for these differences:
- Allows the fraction to be expressed directly (`1/3`) instead of requiring an spelled out variation (`1-of-3`).
- Specifies `u-size-inline` instead of simply `u-size`. This is in support of our embracing logical properties and also to avoid the headaches associated with adding height utilities later on (see the `u-limitHeight*` utilities we had to add last time around).
- Fewer denominators. Previously, we supported 2, 3, 4, 5, 6, 8, 10 and 12. This time I capped it at 6 because I think in the context of articles and pages those will be the …
> Add responsive inline size utilities

- .changeset/fuzzy-beds-breathe.md
- src/components/cloud-cover/cloud-cover.scss
- src/components/cloud-cover/cloud-cover.twig
- src/components/cloud-cover/demo/extra.twig
- src/components/subscribe/demo/demo.twig
- src/components/subscribe/subscribe.scss
- src/components/subscribe/subscribe.stories.mdx
- src/components/subscribe/subscribe.test.ts
- src/components/subscribe/subscribe.twig
- src/tokens/size/rhythm.js
This PR modifies the Subscribe and Cloud Cover components to play nicer together.
It updates the Subscribe component to make the headings optional, and tweaks the layout to switch to horizontal once there's enough space for two buttons, rather than at a fixed breakpoint.
It updates the Cloud Cover component to switch layout at a custom breakpoint (`45em`) rather than `m`, and adjusts the proportion of space between the `content` and `extra` cells to give the `extra` content a bit more room to breathe at mid-size viewports.
1. Review the "Cloud Cover > Extra Content" story on the preview environment at all breakpoints.
1. Review the other Cloud Cover stories for visual regressions.
2. Review the Subscribe component story for visual regressions.
---
- Fixes #1769
> Improve Cloud Cover with Subscribe Combo

- .changeset/cuddly-poems-hang.md
- .changeset/curly-cameras-fix.md
- .changeset/gold-pans-sin.md
- .changeset/sixty-starfishes-nail.md
- src/components/alert/alert.twig
- src/components/badge/badge.twig
- src/components/cloud-cover/demo/extra.twig
- src/components/cloud-cover/demo/scene.twig
- src/components/comment/comment.twig
- src/components/footnote/footnote.twig
- src/components/ground-nav/ground-nav.twig
- src/components/heading/heading.twig
- src/components/icon/demo/a11y.twig
- src/components/icon/icon.stories.mdx
- src/components/icon/icon.twig
- src/objects/rhythm/demo/article.twig
Adds an optional `title` property to the Icon component.
If omitted, icons will now have their `aria_hidden` property set to `"true"`.
If provided, the contents of `title` will be prepended to the SVG contents as `<title>{{title}}</title>` and the `role` will be set to `"img"`. (I started to also add support for specifying a title ID, but that apparently was addressing a Chrome-specific bug that was fixed [more than six years ago](https://bugs.chromium.org/p/chromium/issues/detail?id=566252).)
Based on this, I was able to update a lot of our existing icon usage to no longer specify `aria_hidden` manually. Along the way, I found and fixed a few small bugs:
- The Alert component's icons were setting `aria-hidden` to `1` (easy mistake to make with booleans instead of strings, a good example …
> Icon title feature + related bug fixes

- .changeset/cuddly-dryers-build.md
- src/mixins/_spacing.scss
- src/objects/rhythm/demo/sections.twig
- src/objects/rhythm/rhythm.scss
Our rhythm object supports setting different rhythm for headings than other elements. Previously, this was done by setting a default `--rhythm-headings` property that was set to `var(--rhythm)`. But this actually only cascades as deep as the initial `--rhythm` declaration, which means if you were to set `--rhythm` later on (like in a modifier), the headings won't update in lockstep.
This PR changes the approach. Instead of declaring a default `--rhythm-headings` value, we use `--rhythm` as the fallback in the heading styles (`var(--rhythm-headings, var(--rhythm))`). This works as intended, where headings always default to the value of `--rhythm` _unless_ `--rhythm-headings` is explicitly declared.
Note how the "more sections below" heading does not have consistent rhythm with the sections …
> Fix rhythm heading cascade issue

- .changeset/cuddly-birds-march.md
- .changeset/rare-wasps-fly.md
- src/base/_animation.scss
- src/base/_index.scss
- src/components/button/button.stories.mdx
- src/components/button/button.twig
- src/mixins/_button.scss
- Adds a `aria_disabled` property to our Button component so the `aria-disabled` attribute may be set
- Extends the existing `:disabled` selector to also include `[aria-disabled="true"]`
- Adds styles for an `is-loading` state class to our button mixin
**Note:** This took longer than I thought because I fell down a rabbit hole. I initially wanted to add a `loading` boolean property to the Twig template, but then I noticed that `is-slashed` didn't work that way, then as I was untangling that I noticed some issues with the existing Storybook args, and eventually I found myself halfway into a complete refactor of the stories and template. This PR is an attempt to harvest _just_ the user-facing changes from that work instead.
Animated loading state:
Loading state when the user prefers reduced …
> Add is-loading and aria-disabled to Button

- .changeset/thin-bats-dress.md
- src/components/ground-nav/ground-nav.scss
Our new error patterns now use the dark theme Ground Nav (see #1886). This worked great except for the border colors, which did not use our theme values. This fixes that.
Before | After
--- | ---
Before | After
--- | ---
1. [Open any Ground Nav story in the deploy preview](https://deploy-preview-1894--cloudfour-patterns.netlify.app/?path=/story/components-ground-nav--cloud-four)
2. Observe the usual border color displays at smaller viewport widths
3. Use the "theme" switcher in Storybook to switch to the Dark theme
4. Observe the border color has now changed (should be our darkest blue, same as the outline on the CTA button)
---
- Fixes #1893
> Use theme color for Ground Nav borders

- .changeset/sweet-pumpkins-dance.md
- src/components/cloud-cover/cloud-cover.scss
- src/components/cloud-cover/demo/extra.twig
- src/mixins/_spacing.scss
- src/objects/deck/deck.scss
Makes Cloud Cover column gaps consistent with the Deck layout object to improve visual relationship of `content` and `extra` blocks.
With grid visible…
Before | After
--- | ---
[Review Cloud Cover stories on deploy preview](https://deploy-preview-1896--cloudfour-patterns.netlify.app/?path=/story/components-cloud-cover--extra-content)
---
- Fixes #1880
> More consistent column gaps

- src/components/heading/heading.stories.mdx
- src/objects/deck/deck.stories.mdx
- src/objects/embed/embed.stories.mdx
Some of our source code previews stopped displaying args passed to the
template recently. That seems to be due to the fact that the
`transformSource` function is called repeatedly, and `args` is not
always populated. It looks like `initialArgs` is a safe fallback, and
we already had several spots in the code doing so. This PR updates
a few stories to include the fallback that were missing it.
See https://github.com/storybookjs/storybook/issues/17341#issuecomment-1170922626 for more info.
On the preview deploy, review the following stories and confirm the args are displayed in the source:
---
- Fixes #1883
> Use `initialArgs` as Fallback for `args`

- .changeset/lazy-rockets-swim.md
- src/base/_defaults.scss
- src/design/defaults.stories.mdx
Sets the default `tab-size` for `pre` elements to `2` instead of the baffling browser default of `8`. Should encourage more accessible code samples without compromising horizontal real estate.
1. Open [the code block story](https://deploy-preview-1910--cloudfour-patterns.netlify.app/?path=/story/design-defaults--code-block)
2. Observe that the tab character is occupying the same width as two space characters
---
- Fixes #1907
> `pre { tab-size: 2; }` 🎉

- .changeset/dirty-snails-impress.md
- src/components/alert/alert.stories.mdx
- src/objects/page/demo/example-with-alert.twig
- src/objects/page/page.scss
- src/objects/page/page.stories.mdx
- src/objects/page/page.twig
- src/tokens/size/sizing.js
This PR adds an `alert` block intended for an Alert component to be passed in.
There are styles in the Page object CSS that are applied to the `alert` block wrapper to position the Alert per [design intent](https://v-next--cloudfour-patterns.netlify.app/iframe.html?args=&id=prototypes-single-page--example&viewMode=story).
Smaller viewports | Larger viewports
--- | ---
Preview: https://deploy-preview-1921--cloudfour-patterns.netlify.app/?path=/story/objects-page--example-with-alert
1. Confirm 
---
- Closes #1922
> Add Alert block to Page object

- .changeset/quick-bikes-shop.md
- .style-dictionary/config.js
- src/objects/page/page.scss
- src/tokens/number/z-index.json
- src/tokens/z-index.stories.mdx
- Add `alert` z-index design token
- Use design token in Page object for Alert placement
1. Review new [`z-index` design token documentation](https://deploy-preview-1928--cloudfour-patterns.netlify.app/?path=/story/design-tokens-z-index--page) 
1. Review [example Page object with Alert story](https://deploy-preview-1928--cloudfour-patterns.netlify.app/?path=/story/objects-page--example-with-alert)
---
- Closes #1931
> Add z-index design token

- .changeset/smooth-owls-try.md
- src/vendor/wordpress/demo/alignment.twig
- src/vendor/wordpress/styles/_core-blocks.scss
- src/vendor/wordpress/utilities.stories.mdx
Adds styles for `.wp-block-video` class so the default, center, full and wide alignment options are consistent between WordPress image and video blocks.
[In this story](https://deploy-preview-1930--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-utilities--alignment), mess with the controls and confirm that alignment between the image and video examples are consistent for all alignment options other than left and right.
---
- Fixes #1920
> Add `wp-block-video` alignment options

- .changeset/cyan-lies-arrive.md
- src/objects/container/container.scss
- src/objects/container/container.stories.mdx
- src/objects/container/demo/fill.twig
This PR adds the new `o-container__pad` class, which behaves similarly
to the existing `o-container__fill` & `o-container__fill-pad` classes,
adding the standard container inline padding to a container child.
1. Review the Container > Fill story on the preview deploy
---
- Fixes #1935
> Add `o-container__pad` class

- .changeset/sharp-years-think.md
- src/components/card/card.test.ts
- src/components/card/card.twig
- src/components/card/demo/div.twig
- src/objects/overview/demo/div.twig
- src/objects/overview/overview.test.ts
- src/objects/overview/overview.twig
This PR updates the template for the Card component and Overview object
to check if `tag_name` is a sectioning element like `article` or
`section`, and then change the default for `header_tag_element` and
`footer_tag_element` to either `header`/`footer` or `div`.
This avoids an issue when `header` elements are rendered in a `div`,
it causes useless "banner" landmarks to display in the VO Rotor.
Confirm tests pass on this PR.
Review the Card and Overview stories on the preview deploy. There should be no visual changes.
---
- Fixes #1934
> Add `is_sectioning` check to Card and Overview

- .changeset/cool-dolls-raise.md
- package-lock.json
- src/utilities/display/demo/clearfix.twig
- src/utilities/display/display.scss
- src/utilities/display/display.stories.mdx
This is needed to fix this issue: https://github.com/cloudfour/cloudfour.com-wp/issues/820
https://deploy-preview-1949--cloudfour-patterns.netlify.app/?path=/docs/utilities-display--clearfix
> Add clearfix utility

- .changeset/smart-windows-buy.md
- src/components/comment/comment.test.ts
- src/components/comment/comment.twig
- src/components/comment/demo/data.ts
The comment component assumed that Timber `comment` objects contain a `link` property. They do not.
This removes references to that and uses the hash ID of the comment instead.
[In this story](https://deploy-preview-1952--cloudfour-patterns.netlify.app/?path=/story/components-comment--single), confirm that the permalink (date with a 🔗 icon next to it) links to the comment itself.
---
- Fixes #1948
> Fix comment permalinks

- .changeset/stale-donuts-retire.md
- src/components/sky-nav/sky-nav.scss
- src/components/sky-nav/sky-nav.test.ts
- src/components/sky-nav/sky-nav.ts
- src/components/sky-nav/sky-nav.twig
This PR adds logic to the Sky Nav component to keep progressive enhancement in place, while also avoiding a layout shift on smaller viewports.
BEFORE | AFTER
--- | ---
Cumulative layout shift: `0.441` | Cumulative layout shift: `0`
Notice the menu toggle button is removed in the "After" since, without JS, it's not functional. 
Left: Before
Right: After 
Before | After
--- | ---
The best way to test will be using your local Cloud Four WordPress site. We can use `npm link` to link to this patterns version. 
1. Checkout out the `cloudfour.com-wp` `main` branch locally
2. Checkout this `cloudfour.com-patterns` branch locally
1. `npm ci && npm run build && npm link`
1. In the theme directory: `npm ci && npm link @cloudfour/patterns && npm run build` 
1. Open an incognito window in Chrome
2. …
> Sky Nav: Remove layout shift caused by progressive enhancement

- .changeset/twenty-otters-remain.md
- src/objects/input-group/input-group.scss
When focusing an input in an Input Group, the focus outline would often be cut off by adjacent elements. This sets a `z-index` value of `1` on children with `:focus` to prevent that from happening.
My first choice for the visual appearance of this state would be a focus outline covering the entire focus group. But looking into methods of doing that would really push this from the realm of _layout object_ to the realm of _component_. There is also some complexity to manage between that and buttons that will be reduced when we move away from our focus visible polyfill (which should be possible in the very near future). So for now I'm settling for just fixing the immediate bug. 
Before | After
--- | ---
[Deploy preview](https://deploy-preview-1955--cloudfour-patterns.netlify.app/?path=/story/ …
> Fix for focus outline overlap in input group

- .changeset/fuzzy-stingrays-begin.md
- src/mixins/_ratio-box.scss
This PR addresses a bug where iframe video players like YouTube or
Vimeo used in an Embed object would offset to the left when playing
in Safari, resulting in the left side of the player being cut off.
1. On the deploy environment, visit the Embed > Video story in Safari and play the video. The player should not shift to the right.
---
- Fixes https://github.com/cloudfour/cloudfour.com-wp/issues/828
> Bugfix: Prevent Embedded Video Clipping in Safari

- .changeset/lovely-pans-rush.md
- .changeset/short-clouds-buy.md
- .changeset/tricky-poems-hide.md
- .storybook/main.js
- package-lock.json
- package.json
- src/components/button-swap/button-swap.stories.mdx
- src/components/event-summary/event-summary.stories.mdx
- src/components/media-summary/demo/book.twig
- src/components/media-summary/demo/event.twig
- src/components/media-summary/media-summary.scss
- src/components/media-summary/media-summary.stories.mdx
- src/components/media-summary/media-summary.twig
- src/objects/media/media.stories.mdx
- src/objects/media/media.twig
This PR adds a more generalized Media Summary component that can fulfill the purpose of the Event Summary and other, similar linked content summaries (books, open source projects, etc.). This will allow us to avoid duplicate links in content in a consistent way.
There are a few design changes compared to Event Summary:
- The object no longer scales on hover. This wasn't essential for events, and it felt a bit jarring on larger objects such as books.
- The inclusion of some standard vertical rhythm to make the content feel more balanced.
To facilitate a Media Summary component that directly extends the Media object, `object_class` and `content_class` properties were added to the Media object.
I also installed the Storybook Status add-on to better communicate deprecated components. While I …
> Add Media options, add Media Summary component, deprecate Event Summary component

- .github/workflows/changesets.yml
This switches the release workflow to use node 16. The CI workflow already does.
> Node 16 in release workflow

- .changeset/config.json
- .github/workflows/changesets.yml
- .github/workflows/ci.yml
- CONTRIBUTING.md
- README.md
- src/docs/intro.stories.mdx
I renamed the branch, this updates the code/documentation:
Closes https://github.com/cloudfour/cloudfour.com-wp/issues/789
> Rename references of `v-next` to `main`

- .changeset/tall-socks-train.md
- src/components/author/author.scss
- src/components/author/author.twig
Closes #1967
Before:
After:
https://deploy-preview-1973--cloudfour-patterns.netlify.app/?path=/docs/components-author--basic-usage
> Don't allow line breaks in author names

- .changeset/strange-toys-bake.md
- src/utilities/display/demo/clearfix.twig
- src/utilities/display/demo/inline-block.twig
- src/utilities/display/display.scss
- src/utilities/display/display.stories.mdx
Adds a `u-inline-block` utility class that will be used to make orphan-rescuing in our new website theme more flexible than the current `&nbsp;` solution.
(Also updates the `u-clearfix` story for visual consistency with this one.)
1. [Open this story in deploy preview](https://deploy-preview-1974--cloudfour-patterns.netlify.app/?path=/story/utilities-display--inline-block)
2. Observe that the words "stay together" do stay together unless there is not enough space for both to display on one line
> Add `u-inline-block` utility

- .changeset/giant-otters-grab.md
- .changeset/strange-toys-bake.md
- src/utilities/display/demo/inline-block.twig
- src/utilities/display/demo/rescue-orphan.twig
- src/utilities/display/display.scss
- src/utilities/display/display.stories.mdx
The `u-inline-block` utility was added for a "rescue orphan" function, but it failed to accomplish this very well within links because it would disrupt `text-decoration`. ~This adds a soft default using the `:where` selector so if _anything_ else is setting `text-decoration` on the element, it will take precedence, but otherwise it will inherit from the parent.~ This renames the utility to `u-rescue-orphan` and adds `text-decoration: inherit`.
Before | After
--- | ---
[Deploy preview](https://deploy-preview-1976--cloudfour-patterns.netlify.app/?path=/story/utilities-display--rescue-orphan)
> Replace `u-inline-block` with `u-rescue-orphan`, include `text-decoration` inheritance

- .changeset/big-feet-live.md
- src/components/button/button.stories.mdx
- src/components/button/button.twig
For https://github.com/cloudfour/cloudfour.com-wp/issues/865. I didn't add a demo for it out of laziness and since it is just a plain pass-through there is not much to show.
> Add `aria_labelledby` and `aria_describedby` properties to button component

- .changeset/spotty-owls-pay.md
- src/components/pagination/pagination.twig
This PR conditionally adds `aria-hidden="true"` for when an ellipsis is rendered in the Pagination component.
The best test method will be using your local Cloud Four WordPress site. We can use `npm link` to link to this patterns version. 
1. Checkout out the `cloudfour.com-wp` `main` branch locally
2. Checkout this `cloudfour.com-patterns` branch locally
1. `npm ci && npm run build && npm link`
1. In the theme directory: `npm ci && npm link @cloudfour/patterns && npm run build` 
-  [ ] On the `/thinks`, the Pagination component ellipsis should have `aria-hidden"true"`
1. In the WP repo: `npm uninstall --no-save @cloudfour/patterns && npm i`
2. In the Patterns repo (delete global symlink): `npm uninstall`
---
- Closes #1977
> Use aria-hidden for Pagination component ellipsis

- .changeset/flat-points-smoke.md
- src/components/sky-nav/sky-nav.ts
- src/components/sky-nav/sky-nav.twig
This PR fixes a bug where the content below the Sky Nav menu was not animating open/closed.
Changes include:
- transition the `document.body` instead of all of the wrapper containers
- update demo with more up-to-date header markup
The best test method will be using your local Cloud Four WordPress site via `npm link`.
1. Checkout out the `cloudfour.com-wp` `main` branch locally
2. Checkout this `cloudfour.com-patterns` branch locally
1. `npm ci && npm run build && npm link`
1. In the theme directory: `npm ci && npm link @cloudfour/patterns && npm run build` 
-  [ ] At smaller viewports, the content below the Sky Nav should animate open/closed (try various pages)
1. In the WP repo: `npm uninstall --no-save @cloudfour/patterns && npm i`
2. In the Patterns repo (delete global symlink): `npm …
> Content below Sky Nav animates again

- package-lock.json
- package.json
- src/vendor/wordpress/styles/_utilities.scss
This PR adds `stylelint-scss@4.0.1` as a devDependency. Previously,
this was being implicitly added via the Cloud Four Stylelint config,
which specifies `stylelint-scss@^4.0.0` via Stylelint's recommended
SCSS config. However, there's a bug in v4.0.0 that was fixed in v4.0.1,
and we wanted that fix. Since v4.0.1 was released over 8 months ago
and the configs don't seem to be in a rush to bump the version, we're
doing it by hand. Someday when the recommended config bumps their
version, we could remove this devDependency.
1. Confirm that checks pass on this PR.
---
- Fixes #1890
> Add `stylelint-scss@4.0.1` as a devDependency

- .changeset/lazy-turkeys-eat.md
- src/utilities/border/border.scss
Fixes a bug where our legacy utility classes would display a border on all edges regardless of direction.
Compare deploy preview border utility stories with `main`, confirm no regressions.
> Set a default `border-width`

- package-lock.json
- package.json
- src/vendor/wordpress/styles/_core-blocks.scss
- src/vendor/wordpress/styles/_utilities.scss
Following the discussion in #1992 I've updated our stylelint config to prefer _not_ collapsing adjacent `:not()` selectors.
This PR updates to the latest version of our Stylelint config and un-collapses a few `:not()` selectors.
Check out the WordPress core blocks story for [Image block](https://deploy-preview-2018--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-core-blocks--image), and [alignment](https://deploy-preview-2018--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-utilities--alignment&args=alignment:alignleft) for blocks with a background color, and confirm there are no regressions.
> Update dependency stylelint-config-cloudfour to v6.1.0

- .changeset/soft-maps-grin.md
- src/components/comment/comment.scss
- src/vendor/wordpress/core-element-comparison.stories.mdx
- src/vendor/wordpress/demo/compare-comment.twig
- src/vendor/wordpress/styles/_core-blocks.scss
This PR updates some of the core block styles to better match base
element styles between posts and comments. Specifically:
1. Applying table styles to tables in comments.
2. Removing outdenting from code blocks in comments on legacy posts.
1. On the preview deploy, go to the [Vendor > WordPress > Core Element Comparison > Comments](https://deploy-preview-2022--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-core-element-comparison--comments) page.
1. Confirm that the table has the base table styles applied (border under the `thead`)
1. Confirm that the code block is _not_ outdented.
1. View source, add the `legacy-post` class to the `#root` element.
1. Confirm that the code block is still not outdented. (previously, `legacy-post` would do this)
---
- Fixes #1997
- Fixes …
> Improved Comment Styles

- .changeset/tasty-points-speak.md
- .storybook/preview.js
- package-lock.json
- package.json
- src/design/defaults.stories.mdx
- src/design/demo/theme-content.twig
- src/mixins/_focus.scss
This PR removes the `focus-visible` polyfill in favor of the native `:focus-visible`.
Before | After
--- | ---
Review each before/after and confirm there are no visual differences when tabbing or clicking focusable elements.
- Before: https://cloudfour-patterns.netlify.app/?path=/story/components-alert--dismissable
- After: https://deploy-preview-2032--cloudfour-patterns.netlify.app/?path=/story/components-alert--dismissable
- Before: https://cloudfour-patterns.netlify.app/?path=/story/components-card--link
- https://deploy-preview-2032--cloudfour-patterns.netlify.app/?path=/story/components-card--link
- Before: https://cloudfour-patterns.netlify.app/?path=/story/components-checkbox--enabled
- After: https://deploy-preview-2032--cloudfour-patterns.netlify.app/?path=/story/components-checkb …
> Remove focus-visible polyfill

- .changeset/dry-kangaroos-try.md
- src/components/calendar-date/calendar-date.twig
- src/components/media-summary/demo/event.twig
This PR modifies the Calendar Date component in an attempt to create a better screen reader user experience.
Changes include:
- added a "single-day event" visually hidden note fallback
- refactor component markup to lessen the VoiceOver duplicate date announcment
- enhance NVDA screen reader UX
No visual changes.
Screenshot | NVDA + Firefox | VoiceOver + Safari
--- | --- | ---
Screenshot | NVDA + Firefox | VoiceOver + Safari
--- | --- | ---
Because VoiceOver is silly. It's the only screen reader that exposes the `datetime` attribute. It probably shouldn't. The NVDA UX is much improved, while the VoiceOver UX is also better, even though it's slightly annoying that the `datetime` value is read, causing the date to be announced twice. Nothing we can do about that, and in my opinion, this …
> Enhance Calendar Date screen reader UX

- .changeset/five-parrots-begin.md
- src/vendor/wordpress/core-blocks.stories.mdx
- src/vendor/wordpress/demo/image.twig
- src/vendor/wordpress/styles/_core-blocks.scss
This PR adds the styles for the new "Outlined" block style we added to the Image block in the WordPress theme. Ideally, we would just add the `u-border-small` class directly, but WordPress adds the class to the outermost element — in this case, the `figure` — and we only want the border to apply to the nested `img` element.
_It's subtle, but there's a 1px border around the image._
1. On the preview deploy, go to [Vendor > WordPress > Core Blocks > Image](https://deploy-preview-2039--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-core-blocks--image).
2. In the controls for the story, you can set the style to "Outlined" which will match the markup rendered by WordPress.
3. Verify that an outline is added when you set the Outlined style, and not otherwise.
4. Test in …
> Add CSS for Outlined style for WP Image block

- .changeset/fuzzy-singers-double.md
- src/components/alert/alert.scss
- src/mixins/_spacing.scss
- src/objects/page/demo/example-with-alert.twig
- src/objects/page/page.scss
This PR refactors the Alert component positioning to a `fixed` position with bottom alignment.
Other changes include:
- make drop-shadows darker for light-theme
- added a `$factor` to the `spacing.fluid-padding-inline` and `spacing.fluid-padding-block` mixins for customization
Smaller viewport | Larger viewport
--- | ---
Preview: https://deploy-preview-2044--cloudfour-patterns.netlify.app/iframe.html?args=&id=objects-page--example-with-alert&viewMode=story
Review various viewport sizes, the Alert:
---
- Closes https://github.com/cloudfour/cloudfour.com-wp/issues/869
> Used fixed positioning for Alert component

- .changeset/eleven-dryers-vanish.md
- src/objects/deck/deck.scss
While addressing https://github.com/cloudfour/cloudfour.com-patterns/issues/2002, I noticed that deck objects with only one item were stretching when column counts were not explicitly specified via a modifier. This was due to a misunderstanding of `auto-fit` versus `auto-fill`. This change fixes that, so if two adjacent deck objects have different item counts, they will not have different alignments.
Here is an example Deck with multiple items in it. Note the column widths:
If we remove all but the first card _before_ this PR, the remaining card stretches to fill the space, becoming far too large:
If we do the same _after_ this PR, the card stays the same size regardless of how many siblings it has:
1. [Open one of the deck stories](https://deploy-preview-2047--cloudfour-patterns.netlify.a …
> Fix alignment issue with deck

- .changeset/empty-forks-type.md
- src/vendor/wordpress/demo/group.twig
- src/vendor/wordpress/styles/_core-blocks.scss
Addresses an issue with `.wp-block-group` elements where they wouldn't inherit vertical rhythm from the `.o-rhythm` object. This could not be resolved via WordPress admin settings because the `class` attribute will not impact the `.wp-block-group__inner-container` element.
A common use case for this block is to group floating images and adjacent content. To prevent extra space for showing up, a little bit of a selector hack was used to negate the top margin on items following a left- or right-aligned image block.
Alternatively I could have replaced this fix with `.wp-block-group.o-rhythm > * { @include spacing.vertical-rhythm; }`, but then you'd need to add the class every time, and it wouldn't include a fix for the image alignment feature above. 
Note the lack of space between the …
> Allow WordPress Group blocks to inherit rhythm

- .changeset/hip-numbers-learn.md
- src/objects/rhythm/demo/nesting.twig
- src/objects/rhythm/rhythm.scss
- src/objects/rhythm/rhythm.stories.mdx
By default, a nested rhythm object inherits the `--rhythm` of its parent. In cases where you did _not_ want to inherit the rhythm, however, the containing element would lose its parent `--rhythm`, which necessitated multiple containing elements to overcome.
This PR changes the modifiers so the `--rhythm` is applied to immediate children, which prevents the element itself from losing its own rhythm.
Notice how the list with `compact` spacing runs up against its sibling, even though the containing element has `generous` spacing:
Now the `compact` spacing only applies to the element's children, so the parent spacing is intact:
Open [this story in the deploy preview](https://deploy-preview-2051--cloudfour-patterns.netlify.app/?path=/story/objects-rhythm--nesting&args=amount:generous;nested_amo …
> Fix nested rhythm object issue

- .changeset/good-pandas-applaud.md
- src/vendor/wordpress/core-blocks.stories.mdx
- src/vendor/wordpress/demo/table.twig
- src/vendor/wordpress/styles/_core-blocks.scss
Adds more WordPress Table block styles, which can be supported from our site using `register_block_style`. Revises the core block story to include controls for testing various combinations. This will replace the previous recommended technique of adding component-specific modifier classes to a field, which was a complex and incomplete solution.
Ruled style:
Numeric style:
[Play with controls in this story on the deploy preview](https://deploy-preview-2052--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-core-blocks--table)
---
- See https://github.com/cloudfour/cloudfour.com-wp/issues/532
/CC @Paul-Hebert
> Support more WordPress table styles

- .changeset/breezy-hats-exist.md
- src/components/avatar/avatar.scss
This PR removes the `ratio-box` mixin dependency and switches it out for the CSS `aspect-ratio` property.
Left: before
Right: after
Before: https://cloudfour-patterns.netlify.app/?path=/docs/components-avatar--empty
After: https://deploy-preview-2055--cloudfour-patterns.netlify.app/?path=/docs/components-avatar--empty
---
- #1999
> Use CSS aspect-ratio property for Avatar

- .changeset/real-nails-design.md
- src/components/avatar/avatar.scss
- src/components/card/card.scss
This PR proposes a solution for using the CSS `aspect-ratio` property and removing the `ratio-box` dependency.
Other changes include:
- Remove `ratio-box` import in Avatar CSS (missed this in my last PR)
- Fix a bug where the circle cover variant wasn't a circle
Left: Before
Right: After
I also fixed a bug where the circle wasn't a circle at ~640px wide viewports:
Before: https://cloudfour-patterns.netlify.app/?path=/docs/components-card--cover-image
After: https://deploy-preview-2057--cloudfour-patterns.netlify.app/?path=/docs/components-card--cover-image
---
- #1999
> Use CSS aspect-ratio for Card component

- .changeset/chatty-numbers-perform.md
- src/assets/icons/copy.svg
- src/assets/icons/external.svg
Was playing with some content updates that would benefit from these two icons.
[View on deploy preview](https://deploy-preview-2058--cloudfour-patterns.netlify.app/?path=/docs/design-icons--page)
> Add copy and external icons

- .nvmrc
A few days ago, Node v18 became the latest LTS release. But our Storybook build commands fail in Node v17 or higher.
The reason for this is that Node changed its cryptographic security requirements in version 17. This breaks the way Webpack generates hashes.
After consulting [this StackOverflow thread](https://stackoverflow.com/q/69692842), I had a few options to address this:
1. Run `npm audit fix --force`. This introduces _many_ breaking changes.
2. Set the `NODE_OPTIONS` environment variable to `--openssl-legacy-provider` everywhere. This felt clunky to me.
3. Set [some Webpack options](https://stackoverflow.com/a/73465262). I attempted this, but it turns out those options are only available in Webpack 5, and this project is currently using version 4.
4. Specify the previous LTS …
> Set specific Node version

- .changeset/honest-spoons-reflect.md
- src/vendor/wordpress/styles/_core-blocks.scss
The default styles for WordPress image blocks with captions that are right-, left- or center-aligned use `table` display styles to constrain captions to the width of the image.
That makes less sense for our content, where we often need to include narrow-width screenshots with accompanying explanations that can feel a bit _confined_ in their space. It also makes them less consistent with regular ol' `figure` styles in our larger project.
Before | After
--- | ---
1. View [the Vendor ▸ WordPress ▸ Utilities ▸ Alignment story](https://deploy-preview-2089--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-utilities--alignment&args=alignment:aligncenter) with `aligncenter` selected.
2. Inspect the image and set its width to be smaller than the caption _or_ inspect the caption and …
> Allow captions for centered WordPress Image Blocks to fill their container

- .changeset/twenty-bees-mate.md
- src/assets/icons/download.svg
The `arrow-down` looked a little large and simplistic when juxtaposed with icons like `external` and `copy`.
---
- Fixes #2093
> Add download icon

- .changeset/fresh-moose-draw.md
- .changeset/strange-steaks-sneeze.md
- src/components/input/elastic-textarea.test.ts
- src/components/input/elastic-textarea.ts
- src/components/input/input.scss
- src/components/input/input.stories.mdx
This PR progressively enhances the Elastic Textarea experience by disabling [`resize`](https://developer.mozilla.org/en-US/docs/Web/CSS/resize).
Preview: https://deploy-preview-2098--cloudfour-patterns.netlify.app/?path=/docs/components-input--elastic-textarea
Confirm:
---
- https://github.com/cloudfour/cloudfour.com-wp/issues/945
> Disable resizing for Elastic Textareas

- .changeset/afraid-monkeys-smile.md
- src/components/comment-form/comment-form.twig
- src/components/input/elastic-textarea.test.ts
This PR does a bit of cleanup by removing usage of the `c-input--elastic` modifier. The modifier is no longer needed as of #2098. 
N/A
1. Confirm the [Comment Form](https://deploy-preview-2110--cloudfour-patterns.netlify.app/iframe.html?args=&id=components-comment-form--default-story&viewMode=story) still has Elastic TextArea functionality
---
- https://github.com/cloudfour/cloudfour.com-wp/issues/945
> Remove usage of input "elastic" modifier

- .changeset/eight-experts-refuse.md
- src/components/comment/comment.test.ts
- src/components/comment/comment.twig
- src/components/comment/demo/data.ts
Our comment component was outputting `comment_content` instead of `content`. While this works fine, it prevents any WordPress filters from applying to the comment content, which prevents us from easily enhancing comments with features like server-side syntax highlighting.
I've left the old `comment_content` property as a `default` so this shouldn't be a breaking change.
Compare [the deploy preview comments docs](https://deploy-preview-2129--cloudfour-patterns.netlify.app/?path=/docs/components-comment--single) to [the live version](https://cloudfour-patterns.netlify.app/?path=/docs/components-comment--single). Though the randomized content may differ, functionally there should be no change.
---
- See https://github.com/cloudfour/cloudfour.com-patterns/issues/2107
> Support WordPress/Timber comment content filters

- .changeset/curvy-ears-rule.md
- src/objects/button-group/button-group.scss
- src/objects/list/list.scss
When these two patterns were authored, support for `gap` properties in Flexbox elements was not great. Now [it's up to 92.8%](https://caniuse.com/flexbox-gap), so it feels like we can simplify these a bit.
Review these layout objects for regressions:
> Use flexbox gap instead of negative margins

- .changeset/giant-sheep-bake.md
- src/components/badge/badge.scss
- src/components/badge/badge.stories.mdx
- src/components/badge/badge.twig
Adds styles to `c-badge` to support linked badges. Useful when badged meta data (such as a topic) corresponds to a URL.
> Linked badges

- .changeset/modern-flowers-remember.md
- src/vendor/highlight/_theme.scss
- src/vendor/highlight/demo/legacy.twig
- src/vendor/highlight/demo/samples/js.js
- src/vendor/highlight/highlight.stories.mdx
Highlight.php is two major versions behind Highlight.js. One especially noticeable difference is the relative lack of differentiated keywords in Highlight.php.
This PR adjusts the colors to subtly improve that differentiation. It also adds a precompiled Highlight.php example to help test the backwards compatibility of the Highlight theme.
The biggest visual change is that "titles" are differentiated better from "keywords." Note the `class Bread extends Dough` line.
Before | After
--- | ---
Switching the color of titles made them the same as built-in language filters, so the old color was moved to the new HL11-only `language_` subscope. This is most visible in `console.log`, with `console` (a language default) and `log` (a function title) swapping colors.
Before | After
--- | ---
[Review …
> Improve highlight.php syntax highlighting

- .changeset/shy-bees-doubt.md
- src/objects/article-header/article-header.scss
- src/objects/article-header/article-header.stories.mdx
- src/objects/article-header/article-header.twig
- src/objects/article-header/demo/example.twig
Adds a new layout object for composing an article's title with adjacent meta information. The "eyebrow" is displayed above the other contents visually.
[Try the deploy preview](https://deploy-preview-2137--cloudfour-patterns.netlify.app/?path=/docs/objects-article-header--example)
> Add Article Header layout object

- .changeset/clean-peas-suffer.md
- .changeset/gorgeous-eels-teach.md
- src/components/button/button.scss
- src/components/button/button.stories.mdx
- src/components/button/demo/styles.twig
- src/mixins/_button.scss
This adds a new `c-button--primary` modifier class that lends additional visual emphasis to a button. This was done with a future promotional content element in mind, where the existing buttons appears to blend in to adjacent text a bit too much.
My original instinct was to re-style the default button instead, but in practice I found it difficult to find a new "default" button style with enough contrast in our dark theme that did not blend in with Input Group. I decided a new modifier would be a better option.
~While interacting with Input Group, I rediscovered the issue where our button scale effects would conflict with adjacent elements: Hovering a button in an input group feels off, because the button loses its alignment when it scales up. This also came up in the past when discussing …
> Add primary button modifier

- .changeset/brave-moles-decide.md
- src/components/ground-nav/ground-nav.twig
Uses `c-button--primary` in Ground Nav so the button may appear more visually prominent.
[Deploy Preview](https://deploy-preview-2145--cloudfour-patterns.netlify.app/?path=/docs/components-ground-nav--cloud-four)
> Use primary button in Ground Nav

- .changeset/moody-candles-beg.md
- src/vendor/wordpress/core-blocks.stories.mdx
- src/vendor/wordpress/demo/embed.twig
- src/vendor/wordpress/demo/embed/speakerdeck.twig
- src/vendor/wordpress/demo/embed/youtube.twig
- src/vendor/wordpress/styles/_core-blocks.scss
I attempted to embed a YouTube video using the WordPress "embed" block, but was surprised to see it didn't really apply any meaningful styles. This PR changes that so it will have parity with our other media blocks.
(I also removed usage of the deprecated `defaultValue` property from one of the other demos in the same file.)
Before | After
--- | ---
On the deploy preview, try out:
---
- Fixes #2147
> Add styles for WordPress embed block

- .changeset/nine-jokes-guess.md
- src/vendor/wordpress/core-blocks.stories.mdx
- src/vendor/wordpress/demo/media-text.twig
- src/vendor/wordpress/styles/_core-blocks.scss
- src/vendor/wordpress/styles/_utilities.scss
Introduces customizations to the WordPress Media-Text block styles:
- Uses `gap` instead of `padding` to maintain gutters, improving alignment with adjacent content.
- Applies the same `has-background` containment styles as groups and paragraphs.
- Maintains vertical rhythm of child elements.
- Applies rounded corners to "fill" images.
On narrow screens with mobile stacking enabled:
On wider screens with pretty typical options selected:
On wider screens with several different options selected:
[Open the story on the deploy preview](https://deploy-preview-2151--cloudfour-patterns.netlify.app/?path=/story/vendor-wordpress-core-blocks--media-text) and experiment with the Storybook controls.
---
- Fixes #2146
> Add styles for WordPress Media-Text block

- .changeset/brave-ravens-applaud.md
- .changeset/tasty-otters-type.md
- src/components/badge/badge.stories.mdx
- src/components/badge/badge.twig
- src/objects/form-group/demo/badge.twig
- src/objects/form-group/demo/input.twig
- src/objects/form-group/form-group.scss
- src/objects/form-group/form-group.stories.mdx
- src/objects/form-group/form-group.twig
A marketing page prototype I'm working on includes a content form with a mixture of required and optional fields, which benefit from some note in their respective labels. This PR makes two changes to account for that:
- It modifies the Form Group object to better align child elements of the label.
- It adds a new `parenthetical` property to badges to wrap the label contents in visually hidden parentheses ("Email (Required)" instead of "Email Required").
On the deploy preview, test the [Form Group](https://deploy-preview-2165--cloudfour-patterns.netlify.app/?path=/docs/objects-form-group--basic) and [Comment Form](https://deploy-preview-2165--cloudfour-patterns.netlify.app/?path=/docs/components-comment-form--default-story) patterns to make sure their labels still behave as expected.
> Account for badges in Form Group labels

- src/components/media-link/media-link.scss
While actually using the new Media Link component, I realized the tighter `line-height` was a bit of an overreach, impairing readability for multi-line text at smaller sizes. This removes it in favor of inheriting the parent element's `line-height`.
(I have not included a changeset since Media Link has yet to be released in a published version.)
Before | After
--- | ---
> Allow Media Link to inherit `line-height`

- .changeset/blue-balloons-vanish.md
- src/objects/logo-group/demo/demo.twig
- src/objects/logo-group/logo-group.scss
- src/objects/logo-group/logo-group.stories.mdx
- src/objects/logo-group/logo-group.twig
The Logo Group was designed for the presentation of client logos on our work page, but while prototyping marketing content I encountered a use case for displaying a couple of logos left-aligned within a normal content flow.
Rather than introduce modifier classes that _remove_ functionality, I thought it was more appropriate to start from a less opinionated baseline and to tack on the features. That means that this is a breaking change that will require a small alteration to the template properties of the work page in our WordPress theme.
[Try out the deploy preview](https://deploy-preview-2168--cloudfour-patterns.netlify.app/?path=/docs/objects-logo-group--default-story) in the following browsers:
> Logo Group padding and justification options

- .changeset/cyan-terms-sip.md
- .changeset/quiet-seahorses-marry.md
- src/components/media-link/media-link.scss
- src/objects/hype-group/demo/single.twig
- src/objects/hype-group/hype-group.scss
- src/objects/hype-group/hype-group.stories.mdx
While implementing some of the newer patterns in our WordPress theme, I came across two bugs:
- A Media Link with content that exceeds its container would break out of a Grid or Flex container.
- A Hype Group image with dimensions smaller than the container would appear awkwardly cropped within.
Before | After
--- | ---
In [this story on the deploy preview](https://deploy-preview-2171--cloudfour-patterns.netlify.app/?path=/story/objects-hype-group--multiple):
> Fixes to Media Link and Hype Group dimension issues

- .changeset/flat-bulldogs-worry.md
- src/objects/hype-group/demo/single.twig
- src/objects/hype-group/hype-group.scss
- src/objects/hype-group/hype-group.stories.mdx
In practice, the Hype Group's medium breakpoint was taking effect a bit too early. This PR introduces a custom breakpoint that better suits the typical volume of content.
Before | After
--- | ---
Compare [this story on the deploy preview](https://deploy-preview-2173--cloudfour-patterns.netlify.app/?path=/story/objects-hype-group--multiple) to [the same story on production](https://cloudfour-patterns.netlify.app/?path=/story/objects-hype-group--multiple), verify that the "medium" breakpoint takes effect at wider viewports than before.
> Update Hype Group breakpoint

- .changeset/metal-crabs-pretend.md
- src/utilities/float/demo/float.twig
- src/utilities/float/float.scss
- src/utilities/float/float.stories.mdx
I ran into a limitation hooking up a WordPress block where I really could use some less opinionated float utility classes. So, here we are!
Test [the Storybook story](https://deploy-preview-2177--cloudfour-patterns.netlify.app/?path=/story/utilities-float--direction) using controls in the following browsers:
> Add float utilities

- .changeset/wise-points-sneeze.md
- src/vendor/wordpress/styles/_core-blocks.scss
It turns out that WordPress's default pullquote block styles are rather opinionated and will be injected into a page instead of in block library CSS. This resulted in the blockquotes being much larger than intended and the wrong text color by default.
Font size and text color may still be adjusted via the WordPress block options as before.
Before | After
--- | ---
> Fix WordPress pullquote block sizing bug

- .changeset/six-bottles-retire.md
- src/base/_themes.scss
- src/tokens/color/text.json
Adds a new `color.$text-code` token containing an alpha-transparent version of our base fuchsia, which increases the contrast of inline code elements inside of lighter-gray containers from `4.32` to `4.56`.
Before | After
--- | ---
1. Open up [the inline element story](https://deploy-preview-2182--cloudfour-patterns.netlify.app/?path=/story/design-defaults--inline-elements) in "Canvas" view.
2. Set the "Theme" dropdown to "Light Alt"
3. Open the "Accessibility" tab in Storybook. Insure that there are no violations, especially no "Elements must have sufficient color contrast" violations.
4. Because the color is alpha-transparent, the Accessibility test mentioned in the previous step may show one as "Incomplete." You can use a contrast checker like [Pika](https://superhighfives.com/pika) to …
> Improve inline code contrast

- .changeset/dirty-deers-turn.md
- src/mixins/_font-size.scss
- src/vendor/wordpress/styles/_utilities.scss
[WordPress 5.9 introduced a change to the way that font size classes work](https://make.wordpress.org/core/2022/01/08/updates-for-settings-styles-and-theme-json/). Instead of outputting the classes themselves, they output custom properties with the values as they saw them. While this _should_ make overriding easier, they also made the utility classes use `!important`, so they actually are overriding more aggressively than before.
I researched a few different solutions:
- [WordPress recommends that theme devs style the custom property instead of the class](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#block-font-sizes). Unfortunately, this is not sufficient because the custom property they are outputting gets injected into the `head` after any enqueued …
> Fix for WordPress "small" utility conflict

- .changeset/metal-sloths-help.md
- src/base/_defaults.scss
- src/base/_themes.scss
When designing a new newsletter signup block I noticed that label text felt a little low-contrast compared to in the light theme. This applies the emphasized text color to those elements when the dark theme is applied.
1. On the deploy preview, view [the Objects / Form Group story](https://deploy-preview-2185--cloudfour-patterns.netlify.app/?path=/story/objects-form-group--basic).
2. Using the 🖌️  icon in Storybook, switch to the "dark" or "dark alternate" themes.
3. Confirm that the label text is fully opaque white.
> Increase label contrast in dark theme

- .changeset/quiet-news-impress.md
- src/vendor/mailchimp/_mailchimp.scss
- src/vendor/mailchimp/demo/signup.twig
- src/vendor/mailchimp/mailchimp.stories.mdx
This includes some custom styles for Mailchimp signup forms so custom forms may be embedded without requiring Mailchimp styles or custom block development. Custom? Custom.
Review [deploy preview](https://deploy-preview-2187--cloudfour-patterns.netlify.app/?path=/docs/vendor-mailchimp--signup-form)
> Add styles for Mailchimp signup forms

- .changeset/spicy-badgers-wait.md
- src/vendor/mailchimp/_mailchimp.scss
- src/vendor/mailchimp/demo/signup.twig
- src/vendor/mailchimp/mailchimp.stories.mdx
When using a Mailchimp form within an article, the heading appeared much closer to the preceding content than intended. This was because the vertical rhythm was not being applied to the first child, which was usually a heading that exceeded `1em` in size.
This applies the initial vertical padding to the first element as long as the Mailchimp form is not the `:first-child` of its container.
Before | After
--- | ---
> Mailchimp spacing fix

- .changeset/loud-mice-fail.md
- src/vendor/mailchimp/_mailchimp.scss
I noticed when reviewing a ~soon-to-be-published~ (**edit:** [now published](https://cloudfour.com/thinks/a-new-resource-for-boosting-your-websites-performance/#enter-your-email-to-get-the-checklist-subscribe)) blog post that added our Input Group layout (and by extension our Input and Button component classes) that the Mailchimp styles were breaking some border radius negation. This adds `:not(.c-input)` and `:not(.c-button)` selectors to prevent this from happening.
Confirm that there is no apparent change in the behavior of [the Mailchimp signup form story on the deploy preview](https://deploy-preview-2191--cloudfour-patterns.netlify.app/?path=/story/vendor-mailchimp--signup-form).
> Exclude Mailchimp styles from components

- .changeset/perfect-needles-kick.md
- src/base/_typography.scss
I was reading [one of our recent articles](https://cloudfour.com/thinks/progressively-enhanced-form-validation-part-3-validating-a-checkbox-group/) and noticed that some code snippets had very huge text.
This seems to be resolved by applying our `text-size-adjust` rule to `-webkit-text-size-adjust` as well. This matches [what caniuse says](https://caniuse.com/text-size-adjust) about support for this feature.
Before | After
--- | ---
Unfortunately it's not super clear to me how to reproduce this outside of the context of a blog post, but at least review the code to verify that this seems like a not-very-risky change?
> Fix some code snippets being too large in iOS

- .changeset/pink-bulldogs-invent.md
- src/vendor/highlight/_theme.scss
- src/vendor/highlight/demo/samples/diff.txt
Adds styles for the Highlight `-addition` and `-deletion` token classes. These only set `color` to maintain compatibility with syntax-highlighting code block features like highlighted lines and line numbers, while also maintaining our existing color contrast.
On the deploy preview, view the Highlight story with the "diff" language selected: https://deploy-preview-2195--cloudfour-patterns.netlify.app/?path=/story/vendor-highlight--theme&args=language:diff
Confirm that the deleted line appears red and the added line appears green.
> Improve "diff" highlight support

- .changeset/honest-paws-hug.md
- .changeset/violet-grapes-teach.md
- src/base/_defaults.scss
- src/design/defaults.stories.mdx
- src/vendor/wordpress/core-blocks.stories.mdx
- src/vendor/wordpress/demo/details.twig
- src/vendor/wordpress/styles/_utilities.scss
WordPress 6.3 added a new core "Details" block. This adds some default styles for `defaults` and `summary`, and also makes sure the WordPress block is compatible with background color containers.
Here's what a details block with a background color would look like before. Note the lack of padding or space between paragraphs:
And here's what it looks like after these changes are applied:
On the deploy preview:
Browsers:
---
- See https://github.com/cloudfour/cloudfour.com-wp/issues/1011
> Add styles for `details` and `.wp-block-details`

- .changeset/gentle-cycles-call.md
- src/components/ground-nav/ground-nav-args.js
- src/components/ground-nav/ground-nav.stories.mdx
- src/components/ground-nav/ground-nav.twig
This PR makes a couple changes to make it easier to use the Ground Nav template in WordPress:
- Renames `features` to `feature_count`
- Adds a `block` for both features so the content can be set
Review the Ground Nav page on the preview deploy. It should still show the appropriate number of features in each story.
> Better Ground Nav Options

- .changeset/thin-schools-brush.md
- src/utilities/size/demo/block-size.twig
- src/utilities/size/demo/styles.scss
- src/utilities/size/size.scss
- src/utilities/size/size.stories.mdx
In a recent WordPress change I had use for a `u-block-size-full` util but it didn't exist. This adds both "full" and "auto" size utils for the block direction.
1. Review the new "Block Size" story in Utilities > Size on the preview deploy.
> Add Block Size Utilities

- .changeset/moody-bottles-agree.md
- .changeset/poor-icons-tan.md
- src/components/checkbox/checkbox.stories.mdx
- src/components/checkbox/checkbox.twig
- src/components/radio/demo/styles.scss
- src/components/radio/demo/with-label.twig
- src/components/radio/radio.scss
- src/components/radio/radio.stories.mdx
- src/components/radio/radio.twig
- src/mixins/_toggle-input.scss
- src/vendor/wordpress/styles/_jetpack-blocks.scss
Creates a new Radio component for styling `radio` type inputs and applies those same styles to the Jetpack contact form CSS for consistency with checkboxes.
Before | After
--- | ---
Using the deploy preview, test in the following browsers:
---
- Fixes #2157
> Radio component

- .changeset/thirty-beers-rush.md
- src/components/ground-nav/demo/ground-nav-demo.twig
- src/components/ground-nav/ground-nav-args.js
- src/components/ground-nav/ground-nav.scss
- src/components/ground-nav/ground-nav.stories.mdx
- src/components/ground-nav/ground-nav.twig
This PR fixes a bug where the width of the features for the Ground Nav wasn't quite right. Now, when there are two features, they'll match the width of the Ground Nav content, and when there's one feature, it'll match the width of a `fill-pad` container in the prose-width content above the Ground Nav.
**Two Features**
**One Feature**
**Note:** See comment below for updated screenshots.
1. On the preview deploy, review the Ground Nav stories (particularly the "Cloud Four" and "One Feature" stories) at multiple viewport sizes in the following browsers:
2. Then test again by changing the content of the features to very short strings to ensure the features don't collapse when the content isn't full-width.
> Bugfix: Ground Nav Feature Widths

- .changeset/dry-tables-leave.md
- src/mixins/_button.scss
- src/objects/input-group/input-group.scss
Our newfound emphasis on newsletter signups has increased the prominence of our Input Group layout object, which has made a lingering issue more visible: On hover/active, our button scaling effects make the button appear disconnected from its adjacent input.
At one time I considered removing the scaling effects entirely, but @gerardo-rodriguez convinced me to reconsider. (See #2141)
I explored some alternative effects, but found they didn't work as well across the different interactive elements (pagination links, alert closure, etc.) that rely on the same tokens.
So I decided to expose those scale values as custom properties, so I could reset them _just_ for the Input Group object.
**TL;DR:** Buttons (and similar interactive elements) will continue to scale in most cases, except in Input …
> Restrict Button scaling in Input Groups

- .changeset/warm-trains-rule.md
- src/assets/icons/cube-alt.svg
- src/assets/icons/cube.svg
- src/components/button/button.stories.mdx
Adds `cube` and `cube-alt` icons to represent 3D models.
I added two separate icons because lighting is perceived pretty differently against dark or light backgrounds. In the future this could be dynamic using SVG and CSS, but I didn't want to delay the immediate use case.
---
/CC @spaceninja
> Add cube icons

- .changeset/shaggy-lemons-sleep.md
- src/objects/page/page.scss
When our Page layout object has an alert, its container blocks clicks, text selections, etc. below.
This is an issue when an alert within is hidden but the element itself is not.
We could refactor our alert JavaScript to target a parent element or to extend page directly, but in doing so I found a few unexpected gotchas and complicated layout considerations.
So instead, I've modified the pattern to set `pointer-events` on the alert's container to `none`, then resetting that value for child elements.
With this change, it's now possible to select/click/etc. elements beneath the alert row:
While still being able to interact with content therein:
On the deploy preview, navigate to [the Page Example with Alert story](https://deploy-preview-2217--cloudfour-patterns.netlify.app/?path=/story/objec …
> Fix for page alert pointer-events issue

- .changeset/green-windows-march.md
- src/vendor/wordpress/styles/_core-blocks.scss
At some point, WordPress shipped an update that applied a default `border-width` on table block `td` and `th` elements unless a block style was applied.
This adds `border-width: 0` to those elements by default so they'll be consistent with our table component again.
Before | After
--- | ---
For whatever reason, this issue isn't symptomatic with our imported Gutenberg styles. But it wouldn't hurt to check our stories for the WordPress table block on the deploy preview to make sure this didn't introduce regressions.
> Fixed ugly default borders on WordPress table blocks

- .github/workflows/ci.yml
Puppeteer stopped working on the latest ubuntu version We use Puppeteer for our tests in Pleasantest.
For now we've downgraded to a version of Ubuntu that works. In the future we'll likely need to fix this in the Pleasantest repo or move to a different testing solution
CI should pass
> Fix Puppeteer in CI by specifying Ubuntu version

- .changeset/loud-paws-tease.md
- src/base/_typography.scss
- src/components/heading/heading.scss
- src/design/defaults.stories.mdx
- src/utilities/display/demo/rescue-orphan.twig
- src/utilities/display/display.scss
- src/utilities/display/display.stories.mdx
Sets some default `text-wrap` styles for ~~paragraphs, list items, figure captions,~~ headings and subheadings.
I marked this as a breaking change because it will conflict with the existing techniques in our theme for reducing orphans and widows. Those workarounds will need to be removed when applying this update.
Before | After
--- | ---
> Add `text-wrap` to typographic elements

- package-lock.json
- package.json
This PR resolves a problem with conflicting versions of React being required as a peer dep by some dependencies. Since we don't actually consume React directly, we'll just pick React 17 so npm stops getting upset every time we need to install dependencies.
> Fix Peer Deps

- .changeset/smart-memes-argue.md
- src/base/_defaults.scss
Addresses an issue where code blocks in comments could break the page's horizontal scroll.
Before, you can scroll the document horizontally as far as the overflow content, even though it's clipped by the `<pre>` element. After, horizontal scrolling is only applied to the `<pre>`.
Before | After
--- | ---
I tried, I really tried, to add a test story to this repository. But because the issue's only symptomatic in a comment thread when the `syntax-highlighting-code-block` is applied within a full page, it was going to take me a _lot_ more time to recreate in a story.
You can recreate the fix by visiting https://cloudfour.com/thinks/css-circles/#comment-6111 in a Chromium browser, resizing to a narrow width, inspecting the `<pre>` element, and applying `position: relative` to the existing …
> Fix for overflow scrolling issue

- .changeset/clear-planets-send.md
- src/vendor/lite-youtube/_lite-youtube.scss
- src/vendor/lite-youtube/demo/fallback.twig
- src/vendor/lite-youtube/light-youtube.stories.mdx
Adds a `lite-youtube-fallback` class for fallback links in [`<lite-youtube>` web components](https://github.com/justinribeiro/lite-youtube), in anticipation of an upcoming feature for our theme.
> `lite-youtube` fallback class
